### ISSUE TITLE
Open Source Summit North America 2023

### ISSUE THREAD

**Issue by abbycabs** [GH-Event-Demos/random-name-picker#10]
![image](https://github.com/GH-Event-Demos/random-name-picker/assets/617994/5bd8e6fb-5b86-46d8-bfe6-ad8406667552)

GitHub prize draw at Open Source Summit North America 2023!

🎫 To enter the draw, add a comment at the bottom of this issue 👇
🏆 The prize draw will be drawn at the GitHub Table at approximately 10:30am on Friday May 12th

(assuming sessions are still running on time!)

A couple of T&C's:

* Entry into this raffle will NOT constitute your consent to be contacted for anything else
* We will not be adding you to our marketing database (but if you want to subscribe to our newsletter, [you can do so here](https://resources.github.com/newsletter/))
* The raffle prize cannot be swapped or changed,
* The winner of the prizes at OSS NA 2023 MUST be at the closing of the event when we draw the winners, otherwise we will redraw!

🚀 This site is deployed to GitHub Pages using GitHub Actions. The Actions workflow pulls entrants from commenters of a GitHub Issue.

Good luck and comment below to enter the draw 👇

**Comment by justin0022** [comment]
✅

**Comment by carlsverre** [comment]
while(1) print("raffle entry")

**Comment by MatthewZMD** [comment]
😎

**Comment by gabrielBusta** [comment]
😀

**Comment by chewbakartik** [comment]
Awesome

**Comment by tmanok** [comment]
Boop

**Comment by ShogunPanda** [comment]
🐼

**Comment by vipulgupta2048** [comment]
Heyyo

**Comment by atjustbeinghumaid** [comment]
Pick me!

**Comment by alexanday** [comment]
Meeee

**Comment by FakeShell** [comment]
I'm built different

**Comment by sandeepkanabar** [comment]
❤️ GitHub ❤️

**Comment by takooakes** [comment]
:)

**Comment by gunslingerfry** [comment]
Love you 😍

**Comment by weikequ** [comment]
👌

**Comment by annania** [comment]
🙋🏾‍♀️

**Comment by stanleyphu** [comment]
😎

**Comment by kkajla12** [comment]
👋

**Comment by caligo025** [comment]
🍻

**Comment by K-Rod12** [comment]
hi

**Comment by GeoffGodwin** [comment]
+1 would merge.

**Comment by pnbrown** [comment]
LGTM

**Comment by emreb** [comment]
Hello

**Comment by cvarjao** [comment]
👋

**Comment by AirFusion45** [comment]
👋

**Comment by ivailop7** [comment]
👋🏻

**Comment by vsiravar** [comment]
🤞

**Comment by benjagm** [comment]
🚀

**Comment by bdjr49** [comment]
🙂

**Comment by bikramj** [comment]
GH ♥︎

**Comment by swcurran** [comment]
Hey!

**Comment by prdeman** [comment]
Paul de Man

**Comment by ghazanhaider** [comment]
.txt

ldr r0,=0xdeadbeef
mov r1, 0x0
loop:
str r0, [r1, #1!]
b loop

**Comment by demirkayaender** [comment]
👋

**Comment by PatrickHeneise** [comment]
🤩

**Comment by ovflowd** [comment]
✨

**Comment by ljharb** [comment]
ᕕ( ᐛ )ᕗ

**Comment by emmet0r** [comment]
🤞🏻🤞🏻🤞🏻

**Comment by chewbakartik** [comment]
Awesome

**Comment by jayesh365** [comment]
Lakers in 6

**Comment by LucioMSP** [comment]
I'm in! :)

**Comment by magnologan** [comment]
🥳

**Comment by hochoy** [comment]
Hello!

**Comment by kyletsang** [comment]
👍

**Comment by deivisvieira** [comment]
🎉🎉🎉

**Comment by CCheng1231** [comment]
Yay!

**Comment by alessfg** [comment]
👋

**Comment by jeffmendoza** [comment]
Pick me

**Comment by metasansana** [comment]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCWKeCbp2wmZQNWOgzUWwuQyf7FfRV7Ek4Fu0F+VNGIYwdHxNRkvTUXMX26cH/r/t4bwuhRIZY984v7ajQ+bfo3ouD6sMRTXVeRWsDN9KvzTPSc2XwqDaoSJJbXgtnN+A0TMsHviADhlZx4nxj4B7Welk4honz2N2zx/FEkDw5rPLZZH9bjzDRpzV+2j9YgszpLNZ0ZJJ2l1XAATOzIExwGqgg6TuB71a7nrjYZwKSCvX9ZK+gLd0jRrtlGDybB2xU1KgYrylhK8+WyVjPbQ51emmhUALcqyEsB+4ofvzk5GdrMsAidRi0AVUiyNQrbigTQDdD2CXzJhuE5QPP71SCX3oPnJd91lLdFfzGkxMeebjBTmEhotYjlWZTgdiL8u/KDDbt5hRDuz3IKj8onmOYIMaPCKtQC6onKoyaay0TxciaGv1ucj+mo1lOKo6qKLkVICRr/pfK5Zz7/wOfAN5Cq1qI2mehSohkCnfv9ASplQKe2Sz6k4NQXIgn+yePjSps=

**Comment by mechastorm** [comment]
😁 hello!

**Comment by mhiland** [comment]
Hi!

**Comment by amyfyliang** [comment]
Hello

**Comment by SatanicDrNull** [comment]
47 4e 55 20 6e 6f 74 20 55 6e 69 78

**Comment by cristianfilipe** [comment]
Hi

**Comment by lucacome** [comment]
👋

**Comment by munahaf** [comment]
+1

**Comment by lrusak** [comment]
Yay prizes!!!!

**Comment by EricMountain** [comment]
👍

**Comment by goneall** [comment]
Yes

**Comment by kennethchoe** [comment]
Pick me

**Comment by kennethchoe** [comment]
Can I submit multiple comments to increase my odd?

**Comment by abbycabs** [comment]
Thanks everyone for joining our raffle! Congrats to all the winners 🎉 

Bags:
* @magnologan 
* @SatanicDrNull 
* @kyletsang 
* @cristianfilipe 
* @mhiland 
* @ovflowd 
* @lrusak 
* @bikramj 

GitHub Pro for 1 Year
* @jayesh365 
* @GeoffGodwin 
* @justin0022 
* @hochoy 
* @amyfyliang
