### ISSUE TITLE
GitHub Raffle at Techorama 23 - Leave a comment to enter

### ISSUE THREAD

**Issue by mishmanners** [GH-Event-Demos/random-name-picker#13]
<p align="center">
    <img alt="Random Name Picker for Lucky Draw" src="https://user-images.githubusercontent.com/95615501/189075655-8b5c5012-1f94-4562-93c0-eaef532d2880.png" width="100" />

# Random Name Picker for GitHub prize draw at Techorama 2023!

![banner-code-graph](https://user-images.githubusercontent.com/36594527/205007944-531bd076-1b9b-4f9b-b0eb-ddf284e2d243.png)

:pray: First, huge shout-out to [@icelam](https://github.com/icelam) for a great and simple name picker we could fork and use for the GitHub booth!

:rocket: This site is deployed to GitHub Pages using GitHub Actions. The Actions workflow pulls entrants from commenters of a GitHub Issue.

:ticket: To enter the draw, add a comment at the bottom of this issue 👇 

## 🏆  The prize will be drawn (Wednesday) 3.45pm.

[Check out the original README](https://github.com/GH-Event-Demos/random-name-picker/blob/main/README.md)

---

A couple of T&C's:

- Entry into this raffle will NOT constitute your consent to be contacted for anything else
- We will not be adding you to our marketing database (but if you want to subscribe to our newsletter, [you can do so here](https://resources.github.com/newsletter/))
- The raffle prize cannot be swapped or changed, 
- The winner of the prize at Techorama *MUST* be present when we draw a winner, otherwise we will redraw!

Good luck!

**Comment by mishmanners** [comment]
Yay GitHub!

**Comment by CED0001** [comment]
Hello world!

**Comment by kaiye13** [comment]
Git hub rules!

**Comment by ZaneSchoonraad-bt** [comment]
Initial Comment

**Comment by whytrall** [comment]
Hello GitHub!

**Comment by krzys1u** [comment]
Hello GH

**Comment by Empathies** [comment]
Go github Co-Pilot!

**Comment by WouterBau** [comment]
Well, hello there, GitHub!

**Comment by Mosie1** [comment]
Hello world

**Comment by jochenjonc** [comment]
Please @microsoft replace Azure DevOps with GitHub. 😅

**Comment by NicolaDeClercq** [comment]
testtest123

**Comment by stephanmannaertproicloud** [comment]
Copilot

**Comment by NiDeWe** [comment]
Hello!

**Comment by SteffenJahr** [comment]
Hello from techorama

**Comment by amoerie** [comment]
Hi from Techorama!

**Comment by vsantele** [comment]
Hi github!

**Comment by AndreNobrega** [comment]
First!

**Comment by tomvdb99** [comment]
hello

**Comment by Sepehr10000** [comment]
Hello world!

**Comment by sujithq** [comment]
Hello GitHub

**Comment by Refflected** [comment]
Yeet

**Comment by stevenvdp1** [comment]
Hello world

**Comment by sanderphilipsen** [comment]
Can you win a copilot license?

**Comment by TimVanOnckelen** [comment]
Hello world 🫣

**Comment by hdanau** [comment]
Hello there

**Comment by deryckejeroen** [comment]
I left a comment.

**Comment by Nishok** [comment]
Left a comment I have.

**Comment by MrYi** [comment]
Git Gud

**Comment by ErikMoreau** [comment]
#GitHubRocks & we love stickers!!!

**Comment by ClumsyPenguin** [comment]
Tried

**Comment by BrunoWouters** [comment]
Hi!

**Comment by jonathanva** [comment]
Drop database

**Comment by Tomeroeni** [comment]
Ola chupapi

**Comment by flamingbug** [comment]
Ceci ne pas a winning comment

**Comment by louagej** [comment]
Hi Techorama

**Comment by phasic** [comment]
Looks good to me

**Comment by ewerspej** [comment]
`Console.WriteLine("GitHub rocks!");`

**Comment by stekkedecat** [comment]
Interesting

**Comment by SvenVandenbrande** [comment]
Hello world

**Comment by kepar** [comment]
Pick me!

**Comment by wouker** [comment]
Hello there from techorama

**Comment by Nehekharan** [comment]
Techorama 2023 ❤️

**Comment by AngeloAlfanoc** [comment]
Allo

**Comment by RobinHerbots** [comment]
Hello Techorama 🙋

**Comment by AlexanderNollet1** [comment]
Present 🤓💻

**Comment by RobinLanderloos** [comment]
Fixed the code boss

**Comment by jonasvsaet** [comment]
✅

**Comment by thomieboy** [comment]
This is the winning comment :)

**Comment by joeripardon** [comment]
Github github github hoooooooo

**Comment by brent-broeckx** [comment]
Hello Github, its me! ❤️

**Comment by Gabriel1986** [comment]
Github, continue being awesome 👍

**Comment by boris-dp** [comment]
Techoramaaa

**Comment by collenbrecht** [comment]
Github is awesome!

**Comment by kennycallens** [comment]
Awesome stand

**Comment by masterChiefBenji** [comment]
GitHub is awesome!

**Comment by LuiseFreese** [comment]
42 😉

**Comment by Vetsoo** [comment]
#MSFT @ Techorama

**Comment by MrTheremy** [comment]
Hello there

**Comment by MathijsHofkens** [comment]
This is a comment

**Comment by mrtncls** [comment]
Yay, github @ techorama

**Comment by Tim-Maes** [comment]
SWAG

**Comment by Pvlerick** [comment]
Up

**Comment by ManuDinicola** [comment]
Hey it’s me

**Comment by CasDecelle** [comment]
Nice booth!

**Comment by icecoldfire** [comment]
Hey booth

**Comment by dtkturpal** [comment]
I was here.

**Comment by NielsSerlet** [comment]
"Hello world "

**Comment by SveNord** [comment]
Thanks for the stickers!

**Comment by Arnegeddon** [comment]
Hey!

**Comment by jbrems** [comment]
Pick me!

**Comment by janvandenbussche** [comment]
a comment

**Comment by DennisVanHout** [comment]
Hello World, this is me 🎶

**Comment by Xeiotos** [comment]
+1

**Comment by BramHoubraken** [comment]
Hello Techorama!

**Comment by QuickScoP3s** [comment]
Github at Techorama 2023 🥳
#ExsertusBoys were here

**Comment by seppehoste** [comment]
ggwp

**Comment by Joren-vanGoethem** [comment]
Ooga booga

**Comment by Helmidyh** [comment]
Github at thechorama woop

**Comment by Jempy35** [comment]
I hope i win.

**Comment by RikBoeykens** [comment]
Hiyah

**Comment by BrendanDaley** [comment]
Hello there

**Comment by benjaminvanrenterghem** [comment]
Hello world

**Comment by simonbogaerts** [comment]
Go to the bottom button? 😇

**Comment by RobinAstle** [comment]
In! Pick me!

**Comment by BeneDeus** [comment]
Hello all!

**Comment by wim-vds** [comment]
Best invention for programmeurs

**Comment by Bart-Verboven** [comment]
Have fun

**Comment by KevinEysackers** [comment]
Hello 👋🏻

**Comment by boy-incerta** [comment]
👍

**Comment by Matthias-vdE** [comment]
Hello from the Techorama booth!

**Comment by BerbeDB** [comment]
Loved the talk yesterday of Michelle!

**Comment by Schoof-T** [comment]
Hello from Techorama!

**Comment by Niels-DP** [comment]
Hello world!

**Comment by gverstraete** [comment]
Github at Techorama 🚀🚀🚀

**Comment by Brentenburg** [comment]
Hi

**Comment by steveniamd** [comment]
Definitely checking out GitHub for our version control and CI/CD pipelines thanks to the talk at your booth earlier today. Thanks!

**Comment by SebaVDP** [comment]
Me too

**Comment by BrunoVT1992** [comment]
Hi from Techorama BE

**Comment by kriebb** [comment]
Great hub to be!

**Comment by kevinversavel** [comment]
Hi! Like the stand on Techorama

**Comment by J-Yen** [comment]
Hello from Techorama!

**Comment by saphir54321** [comment]
Having a great time in Techorama 🙂

**Comment by tykamara** [comment]
Hey GitHub @techorama!

**Comment by depressedPEPE** [comment]
Heyo!

**Comment by MrMurc** [comment]
Yay! 🤖

**Comment by cedricdelval** [comment]
Regards from cedsoft!

**Comment by GeoCoder71** [comment]
Hello from Techorama! 🇧🇪🐼

**Comment by PhbsSmn** [comment]
You 🤘

**Comment by RoelantD** [comment]
GitHub for the win 🙌🏻

**Comment by VigoC** [comment]
Hi from Techorama

**Comment by anthony2311** [comment]
Hello github !

**Comment by mmphs** [comment]
I ❤️ GitHub

**Comment by IronCarnage** [comment]
Hello World/Github

**Comment by benborra** [comment]
Anything 🚀

**Comment by SaltyTiefling** [comment]
Here's hoping

**Comment by AnnDeF** [comment]
Booyakashaw!

**Comment by Kalimath** [comment]
Greetings from Techorama 😉

**Comment by celineostijn** [comment]
Yay!

**Comment by CedricVD** [comment]
Hi!

**Comment by mattijs1985** [comment]
Hi Mattijs

**Comment by ChThy** [comment]
Hello GitHub!

**Comment by LauVast** [comment]
Hey!

**Comment by mishmanners** [comment]
Thank you all again for coming to visit our booth at Techorama. We hope you had a great time and looking forward to seeing you at another GitHub event soon 😄
