### ISSUE TITLE
Microsoft Build 2023

### ISSUE THREAD

**Issue by martinwoodward** [GH-Event-Demos/random-name-picker#19]
<p align="center">
<img width="500" alt="Microsoft Build" src="https://github.com/GH-Event-Demos/random-name-picker/assets/856858/33f9ec58-72b7-40f9-a29e-93976865a1d0">
</p>

## GitHub prize draw at Microsoft Build 2023!

:ticket: To enter the draw, add a comment at the bottom of this issue 👇 

### 🏆  The prize draw will be drawn at the GitHub Table on Tuesday and Wednesday.  Check back here or look for an email to let you know if you have won!

A couple of T&C's:

- Entry into this raffle will NOT constitute your consent to be contacted for anything else
- We will not be adding you to our marketing database (but if you want to subscribe to our newsletter, [you can do so here](https://resources.github.com/newsletter/))
- The raffle prize cannot be swapped or changed, 
- The winner of the prizes at Build 2023 *MUST* collect the prize before the end of the conference, otherwise the prize be forfeit!

:rocket: This site is deployed to GitHub Pages using GitHub Actions. The Actions workflow pulls entrants from commenters of a GitHub Issue.

<details>
<summary>Full T&Cs here</summary>

**MICROSOFT GITHUB MSFT BUILD EVENT SWEEPSTAKES
OFFICIAL RULES**

**SPONSOR**

These Official Rules (“Rules”) govern the operation of the Microsoft GitHub MSFT Build Event Sweepstakes (“Sweepstakes”). Microsoft Corporation, One Microsoft Way, Redmond, WA, 98052, USA, is the Sweepstakes sponsor (“Sponsor”).

**DEFINITIONS**

In these Rules, “Microsoft”, “we”, “our”, and “us”, refer to Sponsor and “you” and “yourself” refers to a Sweepstakes participant, or the parent/legal guardian of any Sweepstakes entrant who has not reached the age of majority to contractually obligate themselves in their legal place of residence. “Event” refers to the MSFT Build event held in Seattle, WA, USA. By entering you (your parent/legal guardian if you are not the age of majority in your legal place of residence) agree to be bound by these Rules.  

**ENTRY PERIOD**

The Sweepstakes will operate during regular Event hours from May 23, 2023 to May 24, 2023 (“Entry Period”). 

**ELIGIBILITY**

Open to any registered Event attendee 18 years of age or older who is a legal resident of the 50 United States (including the District of Columbia). If you are 18 years of age or older but have not reached the age of majority in your legal place of residence, then you must have consent of a parent/legal guardian.

Employees and directors of Microsoft Corporation and its subsidiaries, affiliates, advertising agencies, and Sweepstakes Parties are not eligible, nor are persons involved in the execution or administration of this promotion, or the family members of each above (parents, children, siblings, spouse/domestic partners, or individuals residing in the same household). Void where prohibited. 

For business/tradeshow events: If you are attending the Event in your capacity as an employee, it is your sole responsibility to comply with your employer’s gift policies. Microsoft will not be party to any disputes or actions related to this matter. GOVERNMENT EMPLOYEES INCLUDING EDUCATORS: Microsoft is committed to complying with government gift and ethics rules and therefore government and public sector employees are not eligible for this promotion.

**HOW TO ENTER**

No Purchase Necessary.

You will receive one entry by Comment on a GitHub Issue created specifically for this giveaway.

The entry limit is one per person during the Entry Period.

Any attempt by you to obtain more than the stated number of entries by using multiple/different accounts, identities, registrations, logins, or any other methods will void your entries and you may be disqualified. Use of any automated system to participate is prohibited.  

We are not responsible for excess, lost, late, or incomplete entries. If disputed, entries will be deemed submitted by the “authorized account holder” of the email address, social media account, or other method used to enter. The “authorized account holder” is the natural person assigned to an email address by an internet or online service provider, or other organization responsible for assigning email addresses. 

**WINNER SELECTION AND NOTIFICATION**

Pending confirmation of eligibility, potential prize winners will be selected by Microsoft or their Agent from among all eligible entries received at the end of each day during the Entry Period.
	
Winners will be notified at the Event, and must claim the prize before the close of the Event.

Winners will be notified via the contact information provided during entry and may be required to complete a prize claim and tax form (“Forms”). If a selected winner cannot be contacted, is ineligible, fails to claim a prize or fails to return any Forms, the selected winner will forfeit their prize and an alternate winner will be selected time allowing. Only three alternate winners will be selected, after which unclaimed prizes will remain unawarded.

**PRIZES**

The following prizes will be awarded: 

Sixty (60) Grand Prize (s). Each winner will receive:
A(n) Octocat Mona Plushie. Approximate Retail Value (ARV) $19.00.

The ARV of electronic prizes is subject to price fluctuations in the consumer marketplace based on, among other things, any gap in time between the date the ARV is estimated for purposes of these Official Rules and the date the prize is awarded or redeemed. We will determine the value of the prize to be the fair market value at the time of prize award.

The total Approximate Retail Value (ARV) of all prizes: $1,140

We will only award one (1) prize(s) per person. No more than the stated number of prizes will be awarded. No substitution, transfer, or assignment of prize permitted, except that Microsoft reserves the right to substitute a prize of equal or greater value in the event the offered prize is unavailable. Except for applicable manufacturer’s limited warranties and any rights you may have under your local laws, prizes are awarded “AS IS” and WITHOUT WARRANTY OF ANY KIND, express or implied (including any implied warranty of merchantability or fitness for a particular purpose); you assume the entire risk of quality and performance, and should the prizes prove defective, you assume the entire cost of all necessary servicing or repair. Microsoft’s limited warranty terms can be found at [https://support.microsoft.com/warranty](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.microsoft.com%2Fwarranty&data=04%7C01%7Cemilyp%40microsoft.com%7C069964687ee54bcf678408d95c58db19%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637642358969181982%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KtTguwgStjKMIxBsEIDuT9Y%2FW7gZOkafRzzDwtx2gPk%3D&reserved=0), and specifically the U.S. warranty is [here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdownload.microsoft.com%2Fdownload%2F8%2F8%2F3%2F8838B5E7-D05A-429F-BBAD-A92D6199AE39%2FMicrosoft%2520Limited%2520Hardware%2520Warranty-North%2520America.pdf&data=04%7C01%7Cemilyp%40microsoft.com%7C069964687ee54bcf678408d95c58db19%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637642358969191911%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bccsw0c8TOusLZg3qUS%2BP%2BsI%2Fc9Jxij5BWffTa2cWG8%3D&reserved=0). Prize winners may be required to complete and return prize claim and / or tax forms (“Forms”) within the deadline stated in the winner notification. Taxes on the prize, if any, are the sole responsibility of the winner, who is advised to seek independent counsel regarding the tax implications of accepting a prize. By accepting a prize, you agree that Microsoft may use your entry, name, image and hometown online and in print, or in any other media, in connection with this Sweepstakes without payment or compensation to you, except where prohibited by law.

**ODDS**

The odds of winning are based on the number and/or quality of eligible entries received. 

**GENERAL CONDITIONS AND RELEASE OF LIABILITY**

To the extent allowed by law, by entering you agree to release and hold harmless Microsoft and its respective parents, partners, subsidiaries, affiliates, employees, and agents from any and all liability or any injury, loss, or damage of any kind arising in connection with this Sweepstakes or any prize won.

All local laws apply. The decisions of Microsoft are final and binding.

We reserve the right to cancel, change, or suspend this Sweepstakes for any reason, including cheating, technology failure, catastrophe, war, or any other unforeseen or unexpected event that affects the integrity of this Sweepstakes, whether human or mechanical. If the integrity of the Sweepstakes cannot be restored, we may select winners from among all eligible entries received before we had to cancel, change or suspend the Sweepstakes. 

If you attempt or we have strong reason to believe that you have compromised the integrity or the legitimate operation of this Sweepstakes by cheating, hacking, creating a bot or other automated program, or by committing fraud in any way, we may seek damages from you to the full extent of the law and you may be banned from participation in future Microsoft promotions. 

**GOVERNING LAW**

This Sweepstakes will be governed by the laws of the State of Washington, and you consent to the exclusive jurisdiction and venue of the courts of the State of Washington for any disputes arising out of this Sweepstakes.   

**WINNERS LIST**

Send an email to brooklyngyal@github.com with the subject line “MSFT Build winners” within 30 days of May 24, 2023 to receive a list of winners that received a prize worth $25.00 or more.

**PRIVACY**

Your privacy is important to us. Microsoft uses the personal data you provide to notify you of important information about our products, upgrades and enhancements, and to send you information about other Microsoft products and services. We share your personal data with your consent or as necessary to complete any transaction or provide any service you have requested. We also share data with Microsoft-controlled affiliates and subsidiaries; with vendors working on our behalf; when required by law or to respond to legal process; to protect our customers; to protect lives; to maintain the security of our services; and to protect the rights or property of Microsoft. Microsoft is committed to protecting the security of your personal data. We use a variety of security technologies and procedures to help protect your personal information from unauthorized access, use, or disclosure. Your personal data is never shared outside the company without your permission, except under the conditions explained above. For more information about Microsoft’s Privacy Practices, see https://aka.ms/privacy. 

If you believe that Microsoft has not adhered to this statement, please contact us at https://aka.ms/privacyresponse. We will respond to questions within 30 days.​

</details>

Good luck and comment below to enter the draw 👇

**Comment by webfish0** [comment]
Woo hoo!

**Comment by Manojpurohit1004** [comment]
Great !

**Comment by malvikC** [comment]
Awesome!

**Comment by iSeiryu** [comment]
Hi!

**Comment by ramzouza** [comment]
Very niceeee

**Comment by dennisrongo** [comment]
Thanks!

**Comment by rookiejava** [comment]
Go github! 😎

**Comment by moretutors** [comment]
Good stuff

**Comment by vanlabajo** [comment]
I want this!

**Comment by emmcc** [comment]
I am enjoying Microsoft Build!!!

**Comment by HJLeee** [comment]
👋

**Comment by Thompwm** [comment]
Whoop whoop!

**Comment by Liamflowers** [comment]
Tiiiiiiite!

**Comment by campionite** [comment]
Hey there fellas!

**Comment by christineharris-p66** [comment]
Wooo hooo - got my email didn’t cha

**Comment by campionite** [comment]
Hey!!

**Comment by johnburns320** [comment]
What up, Hubbers! Shout out to @martinwoodward!

**Comment by RobotX5** [comment]
Chat looks super cool

**Comment by Riteshsagi** [comment]
Awesome

**Comment by ldeejay** [comment]
Woot

**Comment by westdavidr** [comment]
Awesome demo!

**Comment by montyshashi** [comment]
Nice

**Comment by andregeuze** [comment]
A comment 😏✌️

**Comment by iTiamo** [comment]
Hi there!

**Comment by jorgemaia** [comment]
Helo!!

**Comment by ArmandoLacerda** [comment]
You guys rock!

**Comment by binaryjanitor** [comment]
Thanks for helping cleanup all the bits over the years. Cheers to many many more!

**Comment by sanket-t-shah** [comment]
Nice tool!!!

**Comment by RajeevChan** [comment]
At Build 2023

**Comment by ricardodsanchez** [comment]
Feliz de estar de regreso en persona en un MS Build!

**Comment by ralphkimoden** [comment]
Enter draw

**Comment by devfables** [comment]
GitHub has been integral to my dev contributions over time. Thanks for being awesome and continuing to improve the developer community. :)

**Comment by maxkonyukh** [comment]
This is IDEAL 🤌! Noice!

**Comment by falt86** [comment]
First

**Comment by dylanh930** [comment]
Was here

**Comment by ybot1122** [comment]
hello!!

**Comment by ogay** [comment]
Hello GitHub!

**Comment by GGuerraReply** [comment]
Hi, i’m the winner

**Comment by bargokr** [comment]
I’m never lucky but here goes nothing!

**Comment by jaypk-git** [comment]
Nice github!

**Comment by vnvenkatesh** [comment]
I want github lamp

**Comment by calderast** [comment]
Hello!

**Comment by smalgin** [comment]
Thanks!

**Comment by rahulamlekar** [comment]
Octocats unite!

**Comment by LaputanMachines** [comment]
I'm hot for GitHub 👌

**Comment by j-hulbert** [comment]
I’m hot for GitHub 🔥

**Comment by sdonka** [comment]
Great !!!

**Comment by turibbio** [comment]
turibbio was here!

**Comment by flcnlc2004** [comment]
This is Frederick from Oklahoma GitHub CoPilot is the real deal 🤟🏽

**Comment by amagliano** [comment]
Everything's awesome!

**Comment by PixelFilter** [comment]
Plushy Time 🐙

**Comment by ThisBytes5** [comment]
Hope I win

**Comment by neo-tango** [comment]
#MSBUILD

**Comment by benjaminkaplan** [comment]
BUILD!

**Comment by Nievikins** [comment]
WOOP COPILOT

**Comment by gbralo** [comment]
Let s do this

**Comment by Jason1269** [comment]
Great learning about GitHub Actions and branch protection rules!

**Comment by WadePhsa** [comment]
Look great!

**Comment by zachbugay** [comment]
This looks like really great work!

**Comment by rajasandeep17** [comment]
Thank you for a wonderful demo!

**Comment by Apatel-Costco** [comment]
Fantastic

**Comment by MarkJager1** [comment]
BUILD!

**Comment by ThorstenBruegge** [comment]
Thank you so much for the anwers.

**Comment by msdorachan** [comment]
Pick me pick me

**Comment by TonyH-Truecos** [comment]
I was here.

**Comment by Spatacoli** [comment]
Great tool!

**Comment by jhitze** [comment]
MS Build ftw

**Comment by rgondi-isn** [comment]
Great

**Comment by sbhandary-isn** [comment]
BUILD

**Comment by mrlife** [comment]
👋

**Comment by ScottRumsey** [comment]
🤞🏻

**Comment by zinaibre** [comment]
Ahoj

**Comment by EoinFalconer** [comment]
🚀

**Comment by nshampur** [comment]
Woo hoo

**Comment by tomkiljo** [comment]
Woop woop 🥳

**Comment by blortorbis** [comment]
A raffle???

**Comment by tj94** [comment]
Here to the build! 🍻

**Comment by smothersell** [comment]
Hello!

**Comment by nsteier** [comment]
Yay!

**Comment by RSJason** [comment]
Woot!

**Comment by blacketj** [comment]
Love a raffle.

**Comment by sswart** [comment]
🚀

**Comment by thimobuchheister** [comment]
Build!

**Comment by MatthijsvdVeer** [comment]
Hiiiii 🎉

**Comment by mezzo81** [comment]
Cool

**Comment by bayyadurai-isn** [comment]
MS build

**Comment by mkanandh** [comment]
GitHub advanced security tools for azure devops is awesome - can't wait to try

**Comment by braml** [comment]
Nice

**Comment by AllyChuChu** [comment]
Yay to Build!

**Comment by tom171296** [comment]
#msbuild2023

**Comment by ramdasba** [comment]
Very interesting

**Comment by joshspicer** [comment]
woo!

**Comment by souzasilvio** [comment]
Cool

**Comment by yghia** [comment]
🎉 #builds

**Comment by gnrey16** [comment]
big winner!

**Comment by mbriggs9374** [comment]
Lupita said I should win!!!!

**Comment by GraniteStateHacker** [comment]
😎

**Comment by clevygolf** [comment]
Lupita said I already won

**Comment by chhtw** [comment]
Build!!!

**Comment by BrianWhy** [comment]
Plushy!

**Comment by ronen33** [comment]
Thanks!!

**Comment by duffh** [comment]
Plushie!

**Comment by harrisonlai** [comment]
Hello

**Comment by mehowq** [comment]
Thanks!

**Comment by oradcliffe** [comment]
Hi from Build!

**Comment by cjchiarello** [comment]
Hi from build

**Comment by martin-nisbet** [comment]
Copilot looks amazing!

**Comment by ip-at-philips** [comment]
👍

**Comment by ProfessorMc** [comment]
Looks cool.

**Comment by simongottipalli** [comment]
#github

**Comment by Echo205** [comment]
Awesome! Cool to meet you guys at build

**Comment by Michael-ICS** [comment]
😄

**Comment by kimsey0** [comment]
Octocat FTW!

**Comment by markjbrown** [comment]
Hello from Seattle

**Comment by jasonprahl** [comment]
:)

**Comment by SebastianSchwarzKpark** [comment]
Nice Job Guys

**Comment by glewisorg** [comment]
❤️ GitHub

**Comment by sherija** [comment]
I came here to chew bubble gum and get swag, and I'm all out of bubble gum.

**Comment by vijayakumarsync** [comment]
GitHub

**Comment by dotMorten** [comment]
🤫

**Comment by Alec13355** [comment]
Commenting for drawing

**Comment by GuillermoOdone** [comment]
Great

**Comment by alangarcia528** [comment]
Awesome! MS Build 2023!

**Comment by camiloandresok** [comment]
Hi... !

**Comment by ordaliefr** [comment]
MSBuild !!!

**Comment by mirlenbrink** [comment]
Hi & Thanks!

**Comment by go4jas** [comment]
404

**Comment by Sven97** [comment]
awesome

**Comment by mirapalheta** [comment]
copilot 🚀

**Comment by chenyezhu** [comment]
Hi

**Comment by wpfeitosa** [comment]
Great!!

**Comment by jeffersonwalsh** [comment]
Loved chatting!

**Comment by coleobri** [comment]
Hello :)

**Comment by kreedtek21** [comment]
Thanks for the sticker!

**Comment by amarcus487** [comment]
Hi!

**Comment by nwnerd** [comment]
Awesome

**Comment by JuWeger** [comment]
Awesome Job Guys!

**Comment by kogelnikp** [comment]
Hi!

**Comment by August144** [comment]
😁

**Comment by prerakpatel2** [comment]
Hello!

**Comment by tgolla** [comment]
I now have my next 3D printer project.

**Comment by eliascastro** [comment]
Hola!

**Comment by kavins14** [comment]
Siuuuu

**Comment by Suhan777** [comment]
Yo!! 🤙✈️🇺🇸🌏

**Comment by mschlin** [comment]
Hello world!

**Comment by bhysjulien** [comment]
Number 1

**Comment by mschlin** [comment]
Hello I love MsBuild!

**Comment by dchana7** [comment]
GitHub 4 ever!!!

**Comment by DavidVoeller** [comment]
Wrestling,  freestyle

**Comment by Abdruggi** [comment]
Hi!

**Comment by yougoh** [comment]
Whoooot

**Comment by borja10-dev** [comment]
Magic!

**Comment by Scabellp** [comment]
Hola!!! HELLO!!!

**Comment by danjepp** [comment]
Awesome work guys

**Comment by jacobjohnston** [comment]
Hello!

**Comment by VarletSamuel** [comment]
Miaaw!

**Comment by raff766** [comment]
Hey there!

**Comment by pablom2023** [comment]
Awesome

**Comment by JoachimDheedene** [comment]
Miauwkens

**Comment by SadotD** [comment]
A comment

**Comment by sbiqbe** [comment]
This is great! Thanks for being at MS Build!

**Comment by kumarvelugula** [comment]
Thank you

**Comment by verschaevesiebe** [comment]
Hello World!

**Comment by JohnCarrollCarpenter** [comment]
Thanks!

**Comment by saymon9** [comment]
Thank you!!!

**Comment by qaerdsminion** [comment]
Plushie!

**Comment by cop-jonathanlee** [comment]
Hello!

**Comment by Inapark90** [comment]
Hi GitHub!

**Comment by aleiduki** [comment]
Thanks for the event

**Comment by juanelodelpiero** [comment]
Hi from Mexico

**Comment by piljookwak** [comment]
From Korea!! Really want this!!!!

**Comment by PoisonJL** [comment]
Woo hooooo

**Comment by ohsmetro** [comment]
Hello GitHub Copilot

**Comment by Sstone389** [comment]
Build 23

**Comment by miglaros** [comment]
In full effect

**Comment by TylerMarshall627** [comment]
Nice!

**Comment by cfjedimaster** [comment]
Meow!

**Comment by sanchitmehta** [comment]
Hello!  Waiting for the Swag

**Comment by jwilsoninsight** [comment]
This is the line for swag .

**Comment by scottchanman** [comment]
> <img alt="Microsoft Build" width="500" src="https://user-images.githubusercontent.com/856858/240380590-33f9ec58-72b7-40f9-a29e-93976865a1d0.png">
> 
> ## GitHub prize draw at Microsoft Build 2023!
> 🎫 To enter the draw, add a comment at the bottom of this issue 👇
> 
> ### 🏆 The prize draw will be drawn at the GitHub Table on Tuesday and Wednesday. Check back here or look for an email to let you know if you have won!
> A couple of T&C's:
> 
> * Entry into this raffle will NOT constitute your consent to be contacted for anything else
> * We will not be adding you to our marketing database (but if you want to subscribe to our newsletter, [you can do so here](https://resources.github.com/newsletter/))
> * The raffle prize cannot be swapped or changed,
> * The winner of the prizes at Build 2023 _MUST_ collect the prize before the end of the conference, otherwise the prize be forfeit!
> 
> 🚀 This site is deployed to GitHub Pages using GitHub Actions. The Actions workflow pulls entrants from commenters of a GitHub Issue.
> 
> Good luck and comment below to enter the draw 👇

**Comment by scottchanman** [comment]
Great! Can’t wait to try CoPilot!!!

**Comment by TaffarelJr** [comment]
Official Swag Inspector.
I'm gonna need to take a look at that plushie.

**Comment by subrata1106** [comment]
Hi there

**Comment by robertbaumann** [comment]
Winner…?

**Comment by danardelean** [comment]
Hello

**Comment by Carcamo-ben** [comment]
Prize time

**Comment by ppottorff** [comment]
Hi GitHub!

**Comment by davidokeyode** [comment]
Lo!

**Comment by graham-saunders** [comment]
My favorite color is yellow.

**Comment by martinman-hrbl** [comment]
Too long :)

**Comment by davidjward30** [comment]
Hello

**Comment by sstaedt** [comment]
Hey there

**Comment by stellabei** [comment]
#awesome!

**Comment by alapin1979** [comment]
Cool!!!

**Comment by eric-urban** [comment]
Everyone should be using GitHub Copilot. Thanks!

**Comment by calebjacobo** [comment]
So excited from New Masters Academy!

**Comment by kamalhathi** [comment]
Super cool

**Comment by cjanis25** [comment]
Yay!

**Comment by jlakhan** [comment]
Yay MS Build 2023!

**Comment by ecet230** [comment]
Yo

**Comment by sumigoma** [comment]
Yay

**Comment by rfustino** [comment]
Very excited about copilot!

**Comment by PasWeber** [comment]
Yay MS BUILD

**Comment by paoloaquino-qhr** [comment]
Msbuild

**Comment by atkulp** [comment]
This comment is the best comment

**Comment by phuangcn** [comment]
MS build

**Comment by Dwii** [comment]
👻

**Comment by markl234** [comment]
Marvellous. Truly marvellous.

**Comment by arnoldpistorius** [comment]
Would love to win one 🤓

**Comment by weiguow98** [comment]
Build

**Comment by markbosch** [comment]
Awesome

**Comment by rogeliogamez92** [comment]
Naisu

**Comment by mymrma** [comment]
Yes, me2

**Comment by jhack7** [comment]
👋

**Comment by taxcollector1** [comment]
Build

**Comment by andreipiv** [comment]
Loving it!

**Comment by collabcoders** [comment]
✅

**Comment by Sanrams** [comment]
Awesome

**Comment by shaibarlev** [comment]
Hi good to see you

**Comment by devonhack** [comment]
✅

**Comment by viktarz** [comment]
Build rules!

**Comment by jodyatronin** [comment]
ChatGpt says I should win!

**Comment by viktarzherdetski** [comment]
Build is great!

**Comment by ckaczor** [comment]
Hope everyone is having a good time at Build.

**Comment by Brian-Ashcroft** [comment]
Let’s go Build!!!

**Comment by tstotis86** [comment]
Oh hi

**Comment by tianlongz** [comment]
Happy Microsoft Build!

**Comment by AFenhoff** [comment]
Ms build

**Comment by woinck** [comment]
awesome!

**Comment by jfullerton44** [comment]
Me please

**Comment by A-M-Schmeh** [comment]
Hi,
I love GitHub 😎

**Comment by curib** [comment]
Go GitHub!!

**Comment by sanjeebsarangi** [comment]
It was great meeting you at the GitHub booth.

**Comment by markotikkanencscfi** [comment]
Love you GitHub!

**Comment by CharlieAndLouise** [comment]
Cool

**Comment by Cityonhill93** [comment]
Build 2023!

**Comment by kateract** [comment]
Entered!

**Comment by Andrew-miller-ins** [comment]
build 2023

**Comment by gvazquez-ing** [comment]
I want my SWAG!

**Comment by andyndang** [comment]
Swaggggg!!

**Comment by ideal2545** [comment]
Put me in, coach

**Comment by sarafvikram** [comment]
Go Build 2023

**Comment by ruvyas** [comment]
Build! 2023

**Comment by davidgvh** [comment]
👋

**Comment by ekendra** [comment]
Excitingly waiting for the copilot integration!!!

**Comment by YujiOshima** [comment]
great!

**Comment by mazeltov7** [comment]
🚀🚀

**Comment by henrikrabit** [comment]
Count me in!

**Comment by seoyoonn** [comment]
Build🩵

**Comment by cjdreiss** [comment]
Hey!

**Comment by manuelramirezr** [comment]
Awesome Thanks Lupita for you attention

**Comment by RamjotSingh** [comment]
Make PR better!

**Comment by simplysrv** [comment]
Build!

**Comment by rami-singh** [comment]
Amazing GitHub actions!

**Comment by JamesBettag** [comment]
MSBuild

**Comment by ericweiss98** [comment]
MSBuild 23

**Comment by samarth-raman** [comment]
MSbuild 23

**Comment by Sipesj** [comment]
Pick me!

**Comment by nzubair** [comment]
Entered

**Comment by Gandhisumit** [comment]
Hello there !!!!!!!!

**Comment by kkb2849** [comment]
Great!

**Comment by vmusasia10g** [comment]
Plushy

**Comment by 10100programer** [comment]
GitHub Rocks!

**Comment by 7mako** [comment]
🐱🐙🚀

**Comment by zerowil** [comment]
Ho ho ho!

**Comment by sagarmk** [comment]
🐙

**Comment by NilserikTS** [comment]
Comment 🙃

**Comment by zerowil** [comment]
I'm groo

**Comment by miffyusa2015** [comment]
Get in

**Comment by MartinZikmund** [comment]
Let's go!

**Comment by kdemandante** [comment]
Lupita and Zach have unofficially endorsed this comment/entry

**Comment by nathanwsu** [comment]
Nice!

**Comment by polkanov** [comment]
:octocat:

**Comment by nick-dresang** [comment]
Good luck!!

**Comment by MaggaBeta** [comment]
I Cant wait!

**Comment by kristjanholmar** [comment]
Awsome 

Kristján Hólmar Birgisson

**Comment by troyfitzwater** [comment]
🐙🎉

**Comment by frankwanicka** [comment]
GitHub is the best!

**Comment by hthongdev** [comment]
MS Build 2023

**Comment by raviteja333** [comment]
Woo hoo

**Comment by emendezgolf** [comment]
Great!

**Comment by jklassen** [comment]
:)

**Comment by efetoboreakpoguma** [comment]
Nice!

**Comment by persalmi** [comment]
Hi!

**Comment by cheungjohn** [comment]
Great booth!

**Comment by chinmayv84** [comment]
👍👍

**Comment by kristjk** [comment]
Hi 😎

**Comment by HannahVaschel** [comment]
Plushie!

**Comment by TimPurdum** [comment]
Hi

**Comment by rafaballerini** [comment]
Rafaella Balleriniiiii

**Comment by will-gilmore** [comment]
GitCat

**Comment by RolandoRo** [comment]
RO from TO

**Comment by JBrentJ** [comment]
Hi Lupita!  Is this a bug or feature?

**Comment by ShaunDayaram** [comment]
Your platform is a game-changer for developers. The intuitive interface, combined with a powerful version control system, facilitates both collaboration and independent work. The integrations with external tools streamline our workflows, improving efficiency and software quality. Your platform fosters a vibrant community that encourages learning, networking, and contribution to open-source projects. Keep innovating, GitHub. We eagerly anticipate the future improvements. Thank you for your outstanding service.

**Comment by mitchnieto** [comment]
First build, fingers crossed - copilot has been awesome during my testing over the last few weeks

**Comment by narennayak-github** [comment]
Plushie!!!

**Comment by Jopie64** [comment]
Gimme, I need it! 😜

**Comment by raviteja333** [comment]
Give me , I need it

**Comment by gsenginerd** [comment]
Need the plushie for my kiddo...

**Comment by ApolloZhu** [comment]
Wish :octocat: is also enjoying MSBuild 😁

**Comment by rajasandeep17** [comment]
Enjoying MS Build! 😄

**Comment by atkulp** [comment]
This comment is the best comment

**Comment by pekoricia** [comment]
Hi!

**Comment by yougoh** [comment]
Hello!

**Comment by makichannelgame** [comment]
i love github

**Comment by GuillermoOdone** [comment]
Cool!

**Comment by mokemokepyonpyon** [comment]
love github

**Comment by nathanwsu** [comment]
Hi!!!

**Comment by GuillermoOdone** [comment]
Great prize!

**Comment by gbecerra1982** [comment]
Great solution

**Comment by migacos2002** [comment]
Great event!!

**Comment by andreipiv** [comment]
Great stuff guys

**Comment by MarianoSierra89** [comment]
Hello! Great event

**Comment by GuillermoOdone** [comment]
Woooowww yeah!

**Comment by Michael-ICS** [comment]
This has been an amazing Conference. Thank you Microsoft!
