### ISSUE TITLE
MS Build 2023 (Day 2)

### ISSUE THREAD

**Issue by martinwoodward** [GH-Event-Demos/random-name-picker#34]
<p align="center">
<img width="500" alt="Microsoft Build" src="https://github.com/GH-Event-Demos/random-name-picker/assets/856858/33f9ec58-72b7-40f9-a29e-93976865a1d0">
</p>

## GitHub prize draw at Microsoft Build 2023!

:ticket: To enter the draw, add a comment at the bottom of this issue 👇 

### 🏆  The prize draw will be drawn at the GitHub Table on Tuesday and Wednesday.  Check back here or look for an email to let you know if you have won!

A couple of T&C's:

- Entry into this raffle will NOT constitute your consent to be contacted for anything else
- We will not be adding you to our marketing database (but if you want to subscribe to our newsletter, [you can do so here](https://resources.github.com/newsletter/))
- The raffle prize cannot be swapped or changed, 
- The winner of the prizes at Build 2023 *MUST* collect the prize before the end of the conference, otherwise the prize be forfeit!

:rocket: This site is deployed to GitHub Pages using GitHub Actions. The Actions workflow pulls entrants from commenters of a GitHub Issue.

<details>
<summary>Full T&Cs here</summary>

**MICROSOFT GITHUB MSFT BUILD EVENT SWEEPSTAKES
OFFICIAL RULES**

**SPONSOR**

These Official Rules (“Rules”) govern the operation of the Microsoft GitHub MSFT Build Event Sweepstakes (“Sweepstakes”). Microsoft Corporation, One Microsoft Way, Redmond, WA, 98052, USA, is the Sweepstakes sponsor (“Sponsor”).

**DEFINITIONS**

In these Rules, “Microsoft”, “we”, “our”, and “us”, refer to Sponsor and “you” and “yourself” refers to a Sweepstakes participant, or the parent/legal guardian of any Sweepstakes entrant who has not reached the age of majority to contractually obligate themselves in their legal place of residence. “Event” refers to the MSFT Build event held in Seattle, WA, USA. By entering you (your parent/legal guardian if you are not the age of majority in your legal place of residence) agree to be bound by these Rules.  

**ENTRY PERIOD**

The Sweepstakes will operate during regular Event hours from May 23, 2023 to May 24, 2023 (“Entry Period”). 

**ELIGIBILITY**

Open to any registered Event attendee 18 years of age or older who is a legal resident of the 50 United States (including the District of Columbia). If you are 18 years of age or older but have not reached the age of majority in your legal place of residence, then you must have consent of a parent/legal guardian.

Employees and directors of Microsoft Corporation and its subsidiaries, affiliates, advertising agencies, and Sweepstakes Parties are not eligible, nor are persons involved in the execution or administration of this promotion, or the family members of each above (parents, children, siblings, spouse/domestic partners, or individuals residing in the same household). Void where prohibited. 

For business/tradeshow events: If you are attending the Event in your capacity as an employee, it is your sole responsibility to comply with your employer’s gift policies. Microsoft will not be party to any disputes or actions related to this matter. GOVERNMENT EMPLOYEES INCLUDING EDUCATORS: Microsoft is committed to complying with government gift and ethics rules and therefore government and public sector employees are not eligible for this promotion.

**HOW TO ENTER**

No Purchase Necessary.

You will receive one entry by Comment on a GitHub Issue created specifically for this giveaway.

The entry limit is one per person during the Entry Period.

Any attempt by you to obtain more than the stated number of entries by using multiple/different accounts, identities, registrations, logins, or any other methods will void your entries and you may be disqualified. Use of any automated system to participate is prohibited.  

We are not responsible for excess, lost, late, or incomplete entries. If disputed, entries will be deemed submitted by the “authorized account holder” of the email address, social media account, or other method used to enter. The “authorized account holder” is the natural person assigned to an email address by an internet or online service provider, or other organization responsible for assigning email addresses. 

**WINNER SELECTION AND NOTIFICATION**

Pending confirmation of eligibility, potential prize winners will be selected by Microsoft or their Agent from among all eligible entries received at the end of each day during the Entry Period.
	
Winners will be notified at the Event, and must claim the prize before the close of the Event.

Winners will be notified via the contact information provided during entry and may be required to complete a prize claim and tax form (“Forms”). If a selected winner cannot be contacted, is ineligible, fails to claim a prize or fails to return any Forms, the selected winner will forfeit their prize and an alternate winner will be selected time allowing. Only three alternate winners will be selected, after which unclaimed prizes will remain unawarded.

**PRIZES**

The following prizes will be awarded: 

Sixty (60) Grand Prize (s). Each winner will receive:
A(n) Octocat Mona Plushie. Approximate Retail Value (ARV) $19.00.

The ARV of electronic prizes is subject to price fluctuations in the consumer marketplace based on, among other things, any gap in time between the date the ARV is estimated for purposes of these Official Rules and the date the prize is awarded or redeemed. We will determine the value of the prize to be the fair market value at the time of prize award.

The total Approximate Retail Value (ARV) of all prizes: $1,140

We will only award one (1) prize(s) per person. No more than the stated number of prizes will be awarded. No substitution, transfer, or assignment of prize permitted, except that Microsoft reserves the right to substitute a prize of equal or greater value in the event the offered prize is unavailable. Except for applicable manufacturer’s limited warranties and any rights you may have under your local laws, prizes are awarded “AS IS” and WITHOUT WARRANTY OF ANY KIND, express or implied (including any implied warranty of merchantability or fitness for a particular purpose); you assume the entire risk of quality and performance, and should the prizes prove defective, you assume the entire cost of all necessary servicing or repair. Microsoft’s limited warranty terms can be found at [https://support.microsoft.com/warranty](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.microsoft.com%2Fwarranty&data=04%7C01%7Cemilyp%40microsoft.com%7C069964687ee54bcf678408d95c58db19%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637642358969181982%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KtTguwgStjKMIxBsEIDuT9Y%2FW7gZOkafRzzDwtx2gPk%3D&reserved=0), and specifically the U.S. warranty is [here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdownload.microsoft.com%2Fdownload%2F8%2F8%2F3%2F8838B5E7-D05A-429F-BBAD-A92D6199AE39%2FMicrosoft%2520Limited%2520Hardware%2520Warranty-North%2520America.pdf&data=04%7C01%7Cemilyp%40microsoft.com%7C069964687ee54bcf678408d95c58db19%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637642358969191911%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bccsw0c8TOusLZg3qUS%2BP%2BsI%2Fc9Jxij5BWffTa2cWG8%3D&reserved=0). Prize winners may be required to complete and return prize claim and / or tax forms (“Forms”) within the deadline stated in the winner notification. Taxes on the prize, if any, are the sole responsibility of the winner, who is advised to seek independent counsel regarding the tax implications of accepting a prize. By accepting a prize, you agree that Microsoft may use your entry, name, image and hometown online and in print, or in any other media, in connection with this Sweepstakes without payment or compensation to you, except where prohibited by law.

**ODDS**

The odds of winning are based on the number and/or quality of eligible entries received. 

**GENERAL CONDITIONS AND RELEASE OF LIABILITY**

To the extent allowed by law, by entering you agree to release and hold harmless Microsoft and its respective parents, partners, subsidiaries, affiliates, employees, and agents from any and all liability or any injury, loss, or damage of any kind arising in connection with this Sweepstakes or any prize won.

All local laws apply. The decisions of Microsoft are final and binding.

We reserve the right to cancel, change, or suspend this Sweepstakes for any reason, including cheating, technology failure, catastrophe, war, or any other unforeseen or unexpected event that affects the integrity of this Sweepstakes, whether human or mechanical. If the integrity of the Sweepstakes cannot be restored, we may select winners from among all eligible entries received before we had to cancel, change or suspend the Sweepstakes. 

If you attempt or we have strong reason to believe that you have compromised the integrity or the legitimate operation of this Sweepstakes by cheating, hacking, creating a bot or other automated program, or by committing fraud in any way, we may seek damages from you to the full extent of the law and you may be banned from participation in future Microsoft promotions. 

**GOVERNING LAW**

This Sweepstakes will be governed by the laws of the State of Washington, and you consent to the exclusive jurisdiction and venue of the courts of the State of Washington for any disputes arising out of this Sweepstakes.   

**WINNERS LIST**

Send an email to brooklyngyal@github.com with the subject line “MSFT Build winners” within 30 days of May 24, 2023 to receive a list of winners that received a prize worth $25.00 or more.

**PRIVACY**

Your privacy is important to us. Microsoft uses the personal data you provide to notify you of important information about our products, upgrades and enhancements, and to send you information about other Microsoft products and services. We share your personal data with your consent or as necessary to complete any transaction or provide any service you have requested. We also share data with Microsoft-controlled affiliates and subsidiaries; with vendors working on our behalf; when required by law or to respond to legal process; to protect our customers; to protect lives; to maintain the security of our services; and to protect the rights or property of Microsoft. Microsoft is committed to protecting the security of your personal data. We use a variety of security technologies and procedures to help protect your personal information from unauthorized access, use, or disclosure. Your personal data is never shared outside the company without your permission, except under the conditions explained above. For more information about Microsoft’s Privacy Practices, see https://aka.ms/privacy. 

If you believe that Microsoft has not adhered to this statement, please contact us at https://aka.ms/privacyresponse. We will respond to questions within 30 days.​

</details>

Good luck and comment below to enter the draw 👇

**Comment by shaween18** [comment]
Woohoo!

**Comment by n0elleli** [comment]
I love GitHub so much! My plushie will be a Copilot captain!

**Comment by rwetzeler** [comment]
I love Octocat!

**Comment by jsinh** [comment]
Third one, Go Pilot…. CoPilot. ❤️❤️

**Comment by rafaballerini** [comment]
Do octocats eat insects? Maybe having this plushie right by my side while I code will make the bugs disappear 🫣

**Comment by rameshnlg** [comment]
Cheers octocat ya!!

**Comment by arunkumarnr** [comment]
GitHub is great

**Comment by moisedo** [comment]
Comment! 🤞🏻

**Comment by skgb86** [comment]
GitHub is great..

**Comment by linguu** [comment]
GitHub is the way. I have spoken!

**Comment by beastsoftwareofsweden** [comment]
AddPro is here!

**Comment by Click2CloudRupal** [comment]
Octocat #Build2023

**Comment by johnburns320** [comment]
@martinwoodward is the bomb.com

**Comment by gkudale** [comment]
Amazing individual Adam. Thank you for all things that you shared.

**Comment by jessecoddington** [comment]
https://media.tenor.com/y_qDvEaALjMAAAAM/spongebob-patrick-star.gif

**Comment by spollins** [comment]
Great meeting you all nice convo

**Comment by josephworks** [comment]
Hi all!

**Comment by arturo-ames** [comment]
Excellent stand, go github

**Comment by EoinFalconer** [comment]
Plz plz 🙏

**Comment by abiramirajendran** [comment]
The new security feature is slay and thanks for clarifying my questions. I also excited to use GitHub Copilot and ChatGPT in Codespace.

**Comment by chloe-mandell** [comment]
What do you call eight cats?

**Comment by jgarverick** [comment]
GitHub employs the best developer relations people in the biz. Will force push for prizes!

**Comment by jeffvestal** [comment]
Having a great time at Build

**Comment by kkb2849** [comment]
Hi there

**Comment by Welchen** [comment]
Day 2, let’s go!

**Comment by jamshedd** [comment]
Love it, and hoping to win!

**Comment by namanvs** [comment]
Copilot is intriguing

**Comment by Beardma** [comment]
Loved the workshop Monday! Thanks to the great people at GitHub!!!

**Comment by LucasL53** [comment]
Yay Github! Day 2!!

**Comment by spillersdaniel** [comment]
Amazing! Would love the plushie toy.

**Comment by sproutmaster** [comment]
Github is cool!

**Comment by cheng-andy** [comment]
Thank you GitHub!

**Comment by Chliu81** [comment]
GitHub is so cool 💻

**Comment by glewisorg** [comment]
Still ❤️ GitHub

**Comment by DanielRosenwasser** [comment]
Hello GitHub!

**Comment by ronaldoalberton** [comment]
Hello word 😁

**Comment by krahllucas** [comment]
❤️ GitHub

**Comment by ronaldoalberton** [comment]
Hello World 😁

**Comment by sanjeebsarangi** [comment]
❤️ Github

**Comment by MgSam** [comment]
It is your birthday.

**Comment by nishy2000** [comment]
good gidhub

**Comment by emmcc** [comment]
Microsoft Build is fun!

**Comment by ghadirim** [comment]
My name is Mona! I am missing octocat name pal!

**Comment by torstitollinen** [comment]
Git git git

**Comment by kassenq** [comment]
Love GitHub :)

**Comment by kikoisti123** [comment]
Git!!!

**Comment by alexabramkin** [comment]
I deserve this! For all the suffering 🥲with last support ticket. Still love you guys 🥹

**Comment by guarasat** [comment]
I love github !

**Comment by sswart** [comment]
🚀

**Comment by andregeuze** [comment]
Love 💕 GitHub !

**Comment by joffir** [comment]
I ❤️ copilot

**Comment by blacketj** [comment]
Woohoo

**Comment by nsteier** [comment]
Sweet

**Comment by RSJason** [comment]
Woot!

**Comment by oradcliffe** [comment]
I can feel the good vibes today.

**Comment by cjchiarello** [comment]
Dave says I should win

**Comment by Majd223** [comment]
Hi!

**Comment by IngaWoodsWaight** [comment]
Ahh!! So happy to be here at MSBuild!

**Comment by atahualpaestevez** [comment]
Github always amazing at MSBuild

**Comment by hekape** [comment]
Thx github

**Comment by htepcds** [comment]
I love GitHub!! Thank you for this wonderful product 💗

**Comment by resoajoe** [comment]
Thanks for everything you've built! Looking forward to trying out GitHub chat!

**Comment by Nievikins** [comment]
WOOO COPILOT

**Comment by pekoricia** [comment]
Hi!

**Comment by josephworks** [comment]
Way more signups today

**Comment by KeesV** [comment]
Awesome! ✈️

**Comment by foppenm** [comment]
Copilot X is really awesome!! 🔥🔥🚀🚀

**Comment by jmartorano2021** [comment]
So excited for GitHub copilot x

**Comment by polkanov** [comment]
:octocat:

**Comment by kd34xbr960** [comment]
👍

**Comment by saadkhan9** [comment]
Raffle entry

**Comment by RodolfoGonzalezFernandez** [comment]
wonderful tool

**Comment by don-sata** [comment]
Genial!!?

**Comment by ashwinvijayakumar** [comment]
git reset --heard HEAD

**Comment by dushyankumar6** [comment]
GitHub code spaces are awesome

**Comment by eric-lee-vagaro** [comment]
Endless possibilities

**Comment by jencarr** [comment]
I am still learning more about using GitHub, but it really helpful in keeping track of what changes happen when.

**Comment by raseniero** [comment]
MSBuild

**Comment by tulsaskaterchic** [comment]
Excited to give the copilot a try!

**Comment by alrovach** [comment]
Great to listen Spanish at GitHub Microsoft Build!

**Comment by brauliomsft** [comment]
Super cool stuff!!

**Comment by joalexan2023** [comment]
Awesome great job GitHub

**Comment by rprashanthkumar** [comment]
Copolit is cool

**Comment by spcastellanos** [comment]
Wohoo!

**Comment by peter-hummel** [comment]
Hi!!!

**Comment by hojin-yu** [comment]
I love Copilot!!

**Comment by yougoh** [comment]
Hello!!

**Comment by sugarqM** [comment]
👾

**Comment by echernenko** [comment]
GitHub for the world

**Comment by gabrielsalazar1** [comment]
Hey!

**Comment by HWANG1007** [comment]
This is my first time to join MS build and it's so good 👍

**Comment by RSpallina** [comment]
#Microsoftbuild2023 is awesome!!

**Comment by dluc** [comment]
GitHub ❣️

**Comment by nick-dresang** [comment]
❤️ GitHub

**Comment by pawang169** [comment]
GitHub wow

**Comment by nishy-2000** [comment]
I♥️github

**Comment by Brazenhead8055** [comment]
Hello GitHub 😁

**Comment by irenewang101** [comment]
At MS Build today! Go Github!

**Comment by bargokr** [comment]
Trying again!

**Comment by EnmanuelParedesR** [comment]
Wohoo!

**Comment by ApolloZhu** [comment]
🐙🐱

**Comment by A01374899** [comment]
Yees

**Comment by jochienCHLA** [comment]
Cool stuff!

**Comment by dletteer** [comment]
Awesome

**Comment by anipind** [comment]
🎉 Congratulations, you are a winner of a collectable GitHub plushie Octocat 🎉 !!

You will soon receive an email to the address registered with your GitHub account. Take that email to the swag area (Level 3, room 331) to claim your plushie. They **must** be picked up prior to 6pm on Wednesday, May 24th. After that, you will forfeit your prize.

@gnrey16
@RajeevChan
@zinaibre
@tom171296
@Spatacoli
@vanlabajo
@viktarz
@kristjk
@ruvyas
@chhtw
@rfustino
@thimobuchheister
@Manojpurohit1004
@BrianWhy
@cjanis25
@markjbrown
@bhysjulien
@alangarcia528
@perfp
@kdemandante
@hakkia1
@WadePhsa
@TylerMarshall627
@markbosch
@dylanh930
@collabcoders
@martinman-hrbl
@CharlieAndLouise
@ruvyas
@sstaedt

**Comment by iTiamo** [comment]
Whatsup

**Comment by iTiamo** [comment]
It appears I was too late

**Comment by pops-git** [comment]
Git4life <3

**Comment by htepcds** [comment]
Hello there,

I am sorry, I just realized that I have won a price which doesn’t happen too many times in my life ☹
I got your email in my inbox but it got lost in the sea of GitHub emails (comments).

I know I’m late to the game but would it be possible to send the plushie to my home address in Canada?

My little girl would love to have it 😊

Kind regards,
Hoeurd
