### ISSUE TITLE
GitHub Raffle at Collision 2023 - Leave a comment to enter

### ISSUE THREAD

**Issue by abbycabs** [GH-Event-Demos/random-name-picker#41]
<p align="center">
    <img alt="Random Name Picker for Lucky Draw" src="https://github.com/GH-Event-Demos/random-name-picker/assets/617994/2c6129b4-c882-4177-b856-6da8dd43f132" />

## GitHub Raffle at Collision 2023!

🎫 To enter the draw, add a comment at the bottom of this issue 👇
## 🏆 The prize draw will be drawn at the GitHub Booth at 12pm on Thursday June 29th

A couple of T&C's:

- Entry into this raffle will NOT constitute your consent to be contacted for anything else
- We will not be adding you to our marketing database (but if you want to subscribe to our newsletter, [you can do so here](https://resources.github.com/newsletter/))
- The raffle prize cannot be swapped or changed, 
- The winner of the prize at Collision 2023 *MUST* be present when we draw a winner, otherwise we will redraw!

Good luck!

---

:pray: Huge shout-out to [@icelam](https://github.com/icelam) for a great and simple name picker we could fork and use for the GitHub booth!

:rocket: This site is deployed to GitHub Pages using GitHub Actions. The Actions workflow pulls entrants from commenters of a GitHub Issue.

**Comment by jxballack333** [comment]
Thanks. Awesome opportunity

**Comment by blastdan** [comment]
Thanks for the chat.

**Comment by UltimateThundermaster** [comment]
Nice 👍

**Comment by NaniTheDiu** [comment]
🙏

**Comment by mmvm153** [comment]
Omg, so awesome, can’t wait

**Comment by asephaCan** [comment]
Great booth!

**Comment by bcha92** [comment]
Great booth!

**Comment by vine-trellis** [comment]
Looking forward to the copilot talk!!!

**Comment by JoeTot** [comment]
Visited the booth!

**Comment by JosephWJMaxwell** [comment]
Good luck all

**Comment by shavaine** [comment]
Booth was awesome!

**Comment by secretariuss** [comment]
You are the best

**Comment by kamiyaa** [comment]
🔥🔥🔥🔥

**Comment by miriamdong** [comment]
Cat rules the world!

**Comment by kincma** [comment]
awesome!

**Comment by mikemozg** [comment]
Like the hat at the booth  ;)

**Comment by RuiNian8** [comment]
🥳🥳🥳

**Comment by fouadhellou** [comment]
Awesome!! 💪❤️🔥

**Comment by kebbn** [comment]
Henlo World!

**Comment by loopinarounds** [comment]
Hello!!

**Comment by JimmyChavada** [comment]
Great 👌👌

**Comment by secretariuss** [comment]
I like it!

**Comment by Dermeni** [comment]
Let's go GitHub!

**Comment by yfprime** [comment]
Test comment

**Comment by YagneshP** [comment]
At the booth

**Comment by xavierdmello** [comment]
AI!!

**Comment by HalaaAlii** [comment]
Hiiiii

**Comment by WilliamUW** [comment]
Hello!

**Comment by AhmedAlAmawi** [comment]
🔥🔥🔥

**Comment by robb2828** [comment]
Great hat!

**Comment by Nihal-P** [comment]
Awesome swag!

**Comment by hfyxin** [comment]
Great booth!

**Comment by igagandeep** [comment]
Loved the co-pilot conversation

**Comment by jae186** [comment]
Thank you for the lovely chat :)

**Comment by parks110** [comment]
love this!

**Comment by syedmunawwar** [comment]
Amazing

**Comment by seldajani** [comment]
Swag me 🍕

**Comment by navisrm** [comment]
Delighted to see you at event

**Comment by amnnkaur** [comment]
❤️ github

**Comment by pkudinov** [comment]
I'm in!

**Comment by rkchudha** [comment]
🚀🚀🚀

**Comment by tarun7singh** [comment]
I'm going to win.

**Comment by erwinqxy** [comment]
😎😎

**Comment by quirozity** [comment]
Great connecting with you all at Collision 💥

**Comment by woobz14** [comment]
Thanks!

**Comment by praveensudharsanan** [comment]
Great connection  with you at collision

**Comment by James-WB** [comment]
Thanks GitHub!

**Comment by menemy** [comment]
Copilot is the best!

**Comment by lanierc** [comment]
Hallo

**Comment by abesamiskevin** [comment]
Hello, World!

**Comment by Victoria-DR** [comment]
Booth was great!

**Comment by HassanN1471** [comment]
Github! ❤️

**Comment by jonathan867** [comment]
Nice meeting you!

**Comment by fmbarretto** [comment]
Thanks for the chat

**Comment by kumikorandle** [comment]
thanks!

**Comment by adityadhingra07** [comment]
hello world

**Comment by husseinr** [comment]
Thanks GH!

**Comment by KarimShafie** [comment]
❤️❤️❤️

**Comment by ItsRLuo** [comment]
Great booth!

**Comment by danielljeon** [comment]
💜💜💜

**Comment by moe-san** [comment]
Great conference

**Comment by JaiMorjaria** [comment]
Thanks for the opportunity :)

**Comment by LFClaro** [comment]
Thank you! :)

**Comment by celestewinter** [comment]
Awesome thanks!

**Comment by deelxn** [comment]
Enjoyed visiting your booth! Thank you!

**Comment by D-Joseph** [comment]
Great booth experience !

**Comment by jhayx** [comment]
Jason Etcovitch is awesome 👯

**Comment by sd3kim** [comment]
I love GitHub! ❤️

**Comment by centrinav** [comment]
Best version control system! 🤗

**Comment by dahcheetah** [comment]
Yooo, gg folks

**Comment by amir002001** [comment]
Love github best platform

**Comment by arshamg** [comment]
LGTM

**Comment by Sanparty** [comment]
Nice to meet you!

**Comment by yan-uxd** [comment]
thanks!!

**Comment by IvanMct** [comment]
LGTM!

**Comment by AazainKhan** [comment]
Collision 2023 🔥

**Comment by ssvrichy** [comment]
yessirrrrr!!!!🫶🏼🫶🏼

**Comment by MuchoNacho** [comment]
Thanks for the chat :)

**Comment by adienaag** [comment]
Cool beans!

**Comment by joeauyeung** [comment]
Awesome!

**Comment by mandychoww** [comment]
So cool!

**Comment by pragmatic42** [comment]
Github rocks! 👍

**Comment by cardilo** [comment]
Thanks 😊

**Comment by kaitlinLewis** [comment]
Yay!!

**Comment by michael-han-dev** [comment]
super cool

**Comment by Sizbei** [comment]
LETS GOOOOO

**Comment by Ricram2** [comment]
here at collision!

**Comment by indify-co** [comment]
So cool! Great to meet you 🎉

**Comment by glesperance** [comment]
🔥

**Comment by Shaderpixel** [comment]
Psych!!

**Comment by Simmaj** [comment]
Github is lit🔥🔥🔥

**Comment by Elliestylephotos** [comment]
Ellie

**Comment by ShrinalT** [comment]
LGTM 🫡

**Comment by thisisvaze** [comment]
Awesome ❤️

**Comment by ijzepeda-LC** [comment]
Commit push!

**Comment by alexdrenea** [comment]
Great booth

**Comment by dhlbhavna** [comment]
Lets build from here.

**Comment by schang2023** [comment]
Love the mugs 😃

**Comment by jmphair** [comment]
Sweet! Thank team! 🔥

**Comment by kristinjacobsleis** [comment]
Yay! Can finally comment! Pick me please!

**Comment by Neuroleptique** [comment]
I love GitHub ♥️

**Comment by mvlhotra** [comment]
Woooo 🥳

**Comment by azimhamza** [comment]
GitHub Usage is daily

**Comment by urielcrampton** [comment]
Epiiic!

**Comment by jcytong** [comment]
Colliding with GitHub 🥰

**Comment by gcoakleyjr** [comment]
Awesome!

**Comment by apatel333** [comment]
Yes pls

**Comment by adityapadhye1507** [comment]
Github!!! 💜💜💜

**Comment by Yuseb** [comment]
It was really good talking with you Jason.

**Comment by tarikbelattar** [comment]
Committing

**Comment by tonymach** [comment]
Gotta get the 💼

**Comment by tahvili** [comment]
Kool Ppl

**Comment by BenKurrek** [comment]
Looks good to merge

**Comment by BenKurrek** [comment]
Looks good to merge

**Comment by mobarrats** [comment]
Looking forward to some swag!

**Comment by cherochero9** [comment]
Collision!🚀

**Comment by DaivikGoel** [comment]
Collision

**Comment by MikaelCasavant** [comment]
Collision 4tw

**Comment by TimothyHan** [comment]
Woohoo let's go!

**Comment by emilyjag24** [comment]
yay let’s go!

**Comment by Sonnto** [comment]
I love GitHub too

**Comment by aikendrumca** [comment]
Github A+

**Comment by Kelly-Guan** [comment]
love github!

**Comment by r4z33n4l1** [comment]
git commit -m "I love GitHub"

**Comment by inspiring71** [comment]
Cool!

**Comment by yraheja77** [comment]
The stall with the maximum crowd. My stall was right in front and could not get the goodies. Such was the crowd

**Comment by Sidharth-82** [comment]
Github is very Useful

**Comment by ScottAgirs** [comment]
GitDrawme

**Comment by Ninakarpoff** [comment]
:) awesome!

**Comment by lucaswatts** [comment]
Thanks GitHub!

**Comment by Nevin243** [comment]
LGTM

**Comment by pepesenaris** [comment]
Go collision 🎉

**Comment by ayicho** [comment]
Go Collision

**Comment by johnmal-dev** [comment]
Comment. Raffle. Winner!!!

**Comment by OrngeWorld** [comment]
Visited the booth! Have a good conference!

**Comment by zackorykelly** [comment]
Hello from Collision 2023

**Comment by wtsousa** [comment]
I want GitHub to be my Copilot #collision2023

**Comment by martamitchell** [comment]
Hi guys! It was great to chat with you today.

**Comment by martamitchell** [comment]
Hi guys! It was great to chat with you today.

**Comment by Ma-Raymond** [comment]
Hey! Raymond here!

**Comment by sleshasharma** [comment]
Hello! Slesha here :)

**Comment by biskit1** [comment]
LETS GOOOO!!

**Comment by bjupreti** [comment]
😎

**Comment by Bettaxis** [comment]
Gimme Dat swag for my Github rep!

**Comment by jennyislong** [comment]
Thank you for the GitHub swag 😊

**Comment by imohitarora** [comment]
Mohit raised a PR!! GitHub please approve and merge ✌🏼

**Comment by TheSodaPopPanda** [comment]
Github swag!!

**Comment by geotrieu** [comment]
cool

**Comment by sarbear28** [comment]
Awesome!

**Comment by vreddhi** [comment]
Get me that prize!!

**Comment by KnlnKS** [comment]
Participating!

**Comment by crastars** [comment]
Good luck to all 🩷

**Comment by MVillagomez56** [comment]
V cool!!

**Comment by ChristopherHaydenTodd** [comment]
Hello!

**Comment by EricCao20** [comment]
Good luck to everyone!

**Comment by mariumk** [comment]
It was great meeting you all! 🥰

**Comment by isaacxj** [comment]
Great to meet you guys!!

**Comment by shubhbhalla** [comment]
Thankk youu!

**Comment by itsyurika** [comment]
Good luck to y'all!

**Comment by zeinabfarag** [comment]
Hiii

**Comment by opheliaau** [comment]
Hello world

**Comment by CedHong** [comment]
Hello world indeed

**Comment by collisionsue123** [comment]
Howdy! Great meeting ya guys! 👋

**Comment by yuliiapavlyk** [comment]
Hii!

**Comment by Punit2303** [comment]
Hey it was nice meeting you!!

**Comment by mheipel** [comment]
Great chatting with you at Collision!

**Comment by intelcoder** [comment]
Great meeting you guys😀

**Comment by null-2020** [comment]
It was nice meeting you guys!

**Comment by rae-shi** [comment]
For the ruffle!

**Comment by aliceyang1** [comment]
Thanks

**Comment by trapsidanadir** [comment]
Holla

**Comment by martinsd94** [comment]
🤙

**Comment by Aytak-Sheshkalani** [comment]
Hey guys!

**Comment by blanco-c** [comment]
Nice chatting with you!

**Comment by shruti271** [comment]
I have enjoyed the GitHub lot, feels to have worth

**Comment by bbf-hub** [comment]
It was great to meet you at collision!

**Comment by jkeomany** [comment]
Was at Collision!

**Comment by jasminekchahal** [comment]
thanks!!

**Comment by hmaiakeo** [comment]
Hello GitHub

**Comment by Alvtag** [comment]
Let's win!

**Comment by docclikdev** [comment]
Hello from Doc Clik

**Comment by lindaryan** [comment]
#octocat4life

**Comment by brennardindanan** [comment]
Thanks so much for hosting this raffle! <3

**Comment by arianitp** [comment]
collision ting

**Comment by yangbooom** [comment]
Hello World @Collision

**Comment by SkylarLJY** [comment]
Comment

**Comment by hassan0599** [comment]
Let's gooo!

**Comment by Mtillyer** [comment]
🤓

**Comment by mk1799** [comment]
Thanks for this amazing activity. Let's wait for results.

**Comment by k4meli4** [comment]
😺

**Comment by kirimiz** [comment]
Github merchandise is the best!

**Comment by joyz7** [comment]
Swag looks sick 😎

**Comment by Rockindash** [comment]
Trying for the swag 🤷‍♂️

**Comment by okseeyou** [comment]
I need to git this swag bag 😂

**Comment by martru118** [comment]
Hello from after the after-party

**Comment by qingbo93** [comment]
hello from collision conf

**Comment by belfer24** [comment]
Noone will read this comment. Hi mom!

**Comment by ariellasmo** [comment]
Woohoo!

**Comment by ricardosporto** [comment]
Heeey!

**Comment by huangfuy** [comment]
in for one!

**Comment by josephmje** [comment]
Can't wait!

**Comment by hgh8592** [comment]
Pick me plz

**Comment by lachown** [comment]
🐈‍⬛

**Comment by lukeheo8592** [comment]
Pick me pick me

**Comment by hudsonaishin** [comment]
Big fan 👾

**Comment by mueeza** [comment]
Cool!

**Comment by christopherojo** [comment]
🤔

**Comment by rajvichavada** [comment]
git please pick me as raffle winner 🤭

**Comment by SwethaMaramganty** [comment]
hello world, pls pick me thx 👍🏻🫶🏼🫂

**Comment by ryanvu** [comment]
pickMe()

**Comment by AnselZeng** [comment]
hello world 🥰

**Comment by federicoiltchev** [comment]
Printf

**Comment by swapnils84** [comment]
Great concept, thnx Github

**Comment by JoannaNiemczyk** [comment]
Hey GitHub!

**Comment by Real1236** [comment]
🔥

**Comment by malek-datastreamer** [comment]
`Console.WriteLine("Hello world!");`

**Comment by MichelCodes123** [comment]
Raffle!

**Comment by AditJainn** [comment]
Collision 2023 !!

**Comment by jenydu** [comment]
good booth!

**Comment by Lanky38** [comment]
I am in. Cool stuff

**Comment by ElhamSalimi** [comment]
I love github!

**Comment by AnnaTLai** [comment]
Hey hello

**Comment by izazw** [comment]
Hello Github!

**Comment by Mat2d2** [comment]
Hi!

**Comment by MarceloMeloRJ** [comment]
hi!

**Comment by raines88** [comment]
Great times at Collision!

**Comment by awc2023** [comment]
Thank you!

**Comment by balrajo** [comment]
Collision 2023!

**Comment by eyobodega** [comment]
Console.log(I win)

**Comment by abbycabs** [comment]
Raffle in ~13minutes! Head over to the GitHub booth (E303) to be eligible to WIN!

**Comment by paigethai** [comment]
woot!! let’s go collision!

**Comment by jennyislong** [comment]
🤞🏻🤞🏻🤞🏻

**Comment by JMatt26** [comment]
Raffle in 9. Im gonna win Gig!

**Comment by mueeza** [comment]
Confirm!

**Comment by jennyislong** [comment]
Comfiem

**Comment by domenicpaiva** [comment]
Thank you for the opportunity!!!

**Comment by mateosuburu** [comment]
Lets go!

**Comment by Mat2d2** [comment]
Win

**Comment by TimothyHan** [comment]
Timothy Han

**Comment by hellokitty808** [comment]
Enter :)

**Comment by rkchudha** [comment]
thanks!

**Comment by adaoust** [comment]
Can't wait for Copilot X 🤖🤖

**Comment by VladyslavBelov** [comment]
Have a nice day)

**Comment by Mtillyer** [comment]
Bump

**Comment by jenydu** [comment]
😀

**Comment by Fshwera** [comment]
Hi

**Comment by Fshwera** [comment]
Go Creed go

**Comment by abbycabs** [comment]
Congrats to all our winners!! 
Special shoutout to @danielljeon for winning the timbuk2 backpack grand prize ✨

**Comment by Lanky38** [comment]
Who won??
