### ISSUE TITLE
GitHub Raffle at  Microsoft Build Mexico City 2023 - Leave a comment to enter

### ISSUE THREAD

**Issue by lasr21** [GH-Event-Demos/random-name-picker#44]
<p align="center">
    <img alt="Random Name Picker for Lucky Draw" src="https://user-images.githubusercontent.com/95615501/189075655-8b5c5012-1f94-4562-93c0-eaef532d2880.png" width="100" />

# Random Name Picker for GitHub prize draw at Microsoft Build Mexico City 2023!

![banner-code-graph](https://user-images.githubusercontent.com/36594527/205007944-531bd076-1b9b-4f9b-b0eb-ddf284e2d243.png)

:pray: First, huge shout-out to [@icelam](https://github.com/icelam) for a great and simple name picker we could fork and use for the GitHub booth!

:rocket: This site is deployed to GitHub Pages using GitHub Actions. The Actions workflow pulls entrants from commenters of a GitHub Issue.

:ticket: Para participar en el sorteo, añade un comentario en la parte inferior de este issue 👇 

## 🏆  The prize will be drawn on June 28th a las 15:15

[Check out the original README](https://github.com/GH-Event-Demos/random-name-picker/blob/main/README.md)

---

A couple of T&C's:

- Entry into this raffle will NOT constitute your consent to be contacted for anything else
- We will not be adding you to our marketing database (but if you want to subscribe to our newsletter, [you can do so here](https://resources.github.com/newsletter/))
- The raffle prize cannot be swapped or changed, 
- The winner of the prize at Microsoft Build Mexico City 2023 *MUST* be present when we draw a winner, otherwise we will redraw!

Good luck!

**Comment by lasr2106** [comment]
Holaa, soy una prueba de ganador

**Comment by LucioMSP** [comment]
Demo...

**Comment by fbuenovipn** [comment]
Hey (: !!

**Comment by TuruckMacto** [comment]
Demoooo

**Comment by UrielRojas** [comment]
Hola

**Comment by Nefonfo** [comment]
Gotcha 👁️👄👁️

**Comment by NikoMagafi** [comment]
Holi ^^

**Comment by Misael-Alvarez** [comment]
Punto pai

**Comment by anamdiazs** [comment]
Test Ana Díaz

**Comment by jorge-jrzz** [comment]
Holaaaa 🥸

**Comment by OscarJ290** [comment]
Holaaaa

**Comment by TheK321** [comment]
Holi, espero ganar (: 👀👀👀👀👀

**Comment by maldos23** [comment]
Holis

**Comment by Melendez34** [comment]
Hola! Excelente platica listo para hacer push y pull

**Comment by OscarRangelM** [comment]
Comentandoooo

**Comment by AndreaPinedaM** [comment]
Hola mundo :)

**Comment by jobeto** [comment]
Hola!

**Comment by IsaacIsaias** [comment]
Heeey! :D

**Comment by She-Ly** [comment]
Holaa!

**Comment by JeanRicardoRmzPar** [comment]
Siuu

**Comment by Folkrom** [comment]
I 💗 GitHub

**Comment by Aylin-Mon** [comment]
Holaaa, espero poder ganar esta dinámica muy fan de GitHub 👌🤩😌 muy buena experiencia

**Comment by josedprzz** [comment]
Holaaaaa 🫶🏻🫶🏻🫶🏻

**Comment by VictorHugoChavez** [comment]
Hello

**Comment by xVrzBx** [comment]
Binary Brains presenteee 🤓☝️

**Comment by LuisAldrichGuz** [comment]
GitHub ♥️

**Comment by TuruckMacto** [comment]
Regalenme otra playera de git xd

**Comment by TEKERone** [comment]
Excelente evento, gracias Microsoft México!! c:

**Comment by Thestrals1** [comment]
Hola desde Microsoft Build 🥺

**Comment by EduDN** [comment]
Hello World, Hello AI, Hello Future!! 🤓🖤

**Comment by Bernab-e** [comment]
ARRIBA GIT HUB Y COPILOT 🐙🐱

**Comment by RootMarce** [comment]
Excelentes charlas en el #MsBuildMX 2023 👍🏻

**Comment by PiterPorquer** [comment]
Tuk

**Comment by FedeLim08** [comment]
Hola, es un gusto estar en estas conferencias #GithubCopilot

**Comment by hubumar** [comment]
Saludos desde MS Build!

**Comment by mramirezpe** [comment]
Hola, excelente presentacion :)

**Comment by ErickDevv** [comment]
Hola 🌎

**Comment by javierjacobo10** [comment]
Saludos, buena exposición

**Comment by ThedyPop** [comment]
Buen evento. Like

**Comment by AlejandroCuestaRodriguez** [comment]
Holaa.

**Comment by FelFT** [comment]
Hola

**Comment by Ximyer** [comment]
Hola :)

**Comment by rohana31** [comment]
Hola! Excelente capacitación! Felicidades y saludos del equipo de la Fundación Carlos Slim

**Comment by ItielSanzAXO** [comment]
Hola :)

**Comment by cuevas097** [comment]
Hola

**Comment by Laura-Gonza** [comment]
+ eventos así 🤙🤙🤙

**Comment by MkAngelo** [comment]
Holaaaa xd

**Comment by NataliaHernandezH** [comment]
¡Un saludo a todos y gracias a los que hicieron ésto posible.! ❣️

**Comment by Pamsagui** [comment]
Nos vemos en Talent Land!

**Comment by Unodetantosluises** [comment]
Hola! Excelentes presentaciones.

**Comment by Ros1a2** [comment]
Hola

**Comment by AnaLauraHG** [comment]
Hola!!

**Comment by LuisAldrichGuz** [comment]
Copilot es GOD

**Comment by jesscobedo7** [comment]
Yei! MD BUILD MX

**Comment by dcastrejonm** [comment]
Hola, muy interesantes charlas

**Comment by AcheZeta** [comment]
Holi

**Comment by Taquitos-Alpastor** [comment]
Hola 🐶❤️

**Comment by mramirezpe** [comment]
Excelente presentacion, saludos

**Comment by Laura-Gonza** [comment]
Microsoft

**Comment by JonnyElChido-lang** [comment]
Estuvo padrisimo el evento 10/10 😎

**Comment by Laura-Gonza** [comment]
GitHub rifado!

**Comment by mariorayo** [comment]
Hola

**Comment by RootMarce** [comment]
Excelentes charlas en el MSBuildMX 2023

**Comment by Jacqueline-cis** [comment]
Yesss!

**Comment by JoseAlfredo95** [comment]
.
