### ISSUE TITLE
GitHub Raffle at WeAreDevelopers 2023 - Leave a comment to enter!!

### ISSUE THREAD

**Issue by martinwoodward** [GH-Event-Demos/random-name-picker#48]
## We are Developers Raffle

<p align="center">
<img src="https://github.com/GH-Event-Demos/random-name-picker/assets/856858/55a37f7e-40e5-4a72-99f7-4686999d10c9" width="400px"/>
</p>

:ticket: To enter the draw for an Octocat plushie, add a comment at the bottom of this issue 👇 

## 🏆  The prize will be drawn on 3pm on Jul 28th - **you need to be there to win**!!

:pray: First, huge shout-out to [@icelam](https://github.com/icelam) for a great and simple name picker we could fork and use for the GitHub booth!

:rocket: This site is deployed to GitHub Pages using GitHub Actions. The Actions workflow pulls entrants from commenters of a GitHub Issue.

---

A couple of T&C's:

- Entry into this raffle will NOT constitute your consent to be contacted for anything else
- We will not be adding you to our marketing database (but if you want to subscribe to our newsletter, [you can do so here](https://resources.github.com/newsletter/))
- The raffle prize cannot be swapped or changed, 
- The winner of the prize at WeAreDevelopers *MUST* be present at 3pm on July 28th when we draw a winner, otherwise we will redraw!

Good luck!

**Comment by martinwoodward** [comment]
Hello!!

**Comment by Morgy93** [comment]
I 💚 Copilot & VSCode

**Comment by Lucky-uzukwu** [comment]
Hello from WAD Berlin

**Comment by Inkala** [comment]
I’ll be here at 15h 😬

**Comment by lcorr8** [comment]
Hello from WAD 👋

**Comment by aygulmardanova** [comment]
Hi 👌🏻 let’s try to get the prize

**Comment by evertzner** [comment]
Hello!!

**Comment by quirinziessler** [comment]
Hello

**Comment by alfirak** [comment]
Hello from WeAreDevs Berlin! 👋🏻🤩

**Comment by devskar** [comment]
give me

**Comment by tschokri** [comment]
Gib 😡

**Comment by damir385** [comment]
Hi!

**Comment by hcipek** [comment]
Hello from berlin

**Comment by fenjuer** [comment]
This is a comment

**Comment by lbradley-mm** [comment]
GitHub rules ❤️❤️❤️

**Comment by vipenm** [comment]
🙌

**Comment by wethil** [comment]
LGTM

**Comment by titeic** [comment]
Github rules 🙌

**Comment by tamara027** [comment]
Hello world 👋

**Comment by Natalja1501** [comment]
Hello, GitHub!

**Comment by MariusAquarius** [comment]
GitHub ftw!!

**Comment by laxmisku56** [comment]
GitHub ai smart way to integrate

**Comment by matiasalbarello** [comment]
Hello world!

**Comment by fraveira** [comment]
Hello!

**Comment by sebastianhomeier** [comment]
LGTM

**Comment by Chanchalesh** [comment]
we dev confrence

**Comment by ole361** [comment]
Hello there!

**Comment by thealeinjo** [comment]
Love it!

**Comment by SemmelJochen** [comment]
Hello there :)

**Comment by auraherrera** [comment]
Nice!

**Comment by arthurmmoreira** [comment]
Nice!

**Comment by SinisaJB** [comment]
Hi! Let's get the prize.

**Comment by yat90** [comment]
Best issue i ever read😁

**Comment by jonaswascheroh** [comment]
#WeAreDevelopers

**Comment by swtw122** [comment]
Hi from Berlin ♥️

**Comment by maximilianbayerl** [comment]
Hi

**Comment by mitrpathak** [comment]
Hey 👋

**Comment by Lnferrari** [comment]
Best issue ever! 😂

**Comment by maximusD9** [comment]
Hola

**Comment by lennertderyck** [comment]
![v1lbpim76kj77pnx6582](https://github.com/GH-Event-Demos/random-name-picker/assets/37124772/9a0c8ad5-0ac4-4e37-a421-07d39cbd02e7)

**Comment by dzhahaiev** [comment]
Lgtm!

**Comment by kaizencodes** [comment]
Hello bello

**Comment by jsrubio** [comment]
Hi from WAD!

**Comment by BennyDeBock** [comment]
Hello there

**Comment by bknasmueller** [comment]
👋

**Comment by abulwcse** [comment]
Hello

**Comment by EmadMokhtar** [comment]
Hello World

**Comment by isadoral** [comment]
awesomeee

**Comment by madmarcinadamski** [comment]
Hi there

**Comment by beardred** [comment]
Hello World

**Comment by MuhammadAbdullahNaseer** [comment]
Hi

**Comment by bebez024** [comment]
418 Im a teapot

**Comment by Mishco** [comment]
Hello Github 🖥

**Comment by Will-Mann-16** [comment]
We love GitHub!

**Comment by TommoLeedsy** [comment]
Loving WAD and the GitHub Booth is the best!!

**Comment by alessio-libardi** [comment]
Awesome

**Comment by shadowmaru** [comment]
Ship it! :shipit:

**Comment by slonoslonko** [comment]
hello

**Comment by thedutchruben** [comment]
Hello

**Comment by DonRobo** [comment]
Hi

**Comment by greefyleans** [comment]
Great talking to you guys today, very enlightening!

**Comment by rlindner** [comment]
Hello from your booth neighbours!

**Comment by falcon1812** [comment]
No code is the best code! Change my mind.

**Comment by sbehrends** [comment]
`git pull octocat`

**Comment by daklin2** [comment]
Hello github:)

**Comment by peterhuszti** [comment]
hello!

**Comment by egertak** [comment]
Hello!

**Comment by nachtgold** [comment]
Hi from Dresden

**Comment by mattumotu** [comment]
Hello

**Comment by TheSnowyxGIT** [comment]
Vive toulouse

**Comment by birterohden** [comment]
woop woop ✨

**Comment by hieu-t-code** [comment]
I want to win

**Comment by bulliana** [comment]
not bad not bad!

**Comment by pkh501** [comment]
Swag pls

**Comment by apuyou** [comment]
😎

**Comment by papotte** [comment]
Hello world!

**Comment by julischa** [comment]
💅🏼💖

**Comment by AlexKrupa** [comment]
What _is_ a comment?

**Comment by leonshenprojects** [comment]
Hellooooooooooooo!

**Comment by timia2109** [comment]
Hello GitHub! I love the bag you gave me 😍

**Comment by J61n** [comment]
Hello from WeAreDevelopers Berlin! 🤙

**Comment by ma3u** [comment]
Great to see you all on @wearedevelopers.

**Comment by tfonfara** [comment]
Nice stickers ❤️

**Comment by DonkiKoi** [comment]
Love the stickers ❤️

**Comment by sunsided** [comment]
Ship It!

**Comment by esthereklund** [comment]
🙌🏻

**Comment by maxizu** [comment]
We are Devs! 🤘😎

**Comment by rosskopfsache** [comment]
WAD 😎

**Comment by Fexiven** [comment]
Hey there~

**Comment by SloopyNoSleep** [comment]
Howdy!

**Comment by mstrangfeld** [comment]
I like trains

**Comment by cslux** [comment]
You are awesome 😎

**Comment by Krakenus** [comment]
Hey there!

**Comment by hansek** [comment]
Cheers

**Comment by SilvijaG1302** [comment]
Hello there

**Comment by andrbmgi** [comment]
Wohoooooo

**Comment by shraddha-5588** [comment]
Helloooo! Love GitHub ❤️❤️❤️

**Comment by eschoemann** [comment]
Hello!

**Comment by bartholomej** [comment]
My hovercraft is full of eels

**Comment by ToniaR** [comment]
Hello GitHub 🤩❤️

**Comment by Jhuniphas** [comment]
Hi GitHub 💚🙈

**Comment by Applepie93** [comment]
👋

**Comment by Nali-zoi** [comment]
Hello from WeAreDevelopers Berlin!

**Comment by negue** [comment]
Fingers crossed for the win =D

**Comment by gruhn** [comment]
I want that plushy 😄

**Comment by lukmarr** [comment]
We are developers! 😎🥳

**Comment by jellypyu** [comment]
I 💖 octocat! ✨✨✨

**Comment by memohseni** [comment]
GitHub is amazing

**Comment by ahmetoner** [comment]
Hello :)

**Comment by piximos** [comment]
Yooo!

**Comment by kolivanne** [comment]
Hallo mit o

**Comment by kalu-o** [comment]
Hallo

**Comment by lscarpi** [comment]
Let's go!

**Comment by emir97** [comment]
Hello from WAD2k23 Berlin

**Comment by MashaP5** [comment]
Hello!! ☀️

**Comment by ena-vul** [comment]
Hii!

**Comment by sheralam** [comment]
Hello world!!

**Comment by tariksuta** [comment]
<hello>to</world>

**Comment by andrewbayd** [comment]
Good luck to me 😅

**Comment by jabberwoc** [comment]
🦖

**Comment by tjarbo** [comment]
Hi GitHub 👋

**Comment by rz-p** [comment]
Hi GitHub ✨

**Comment by Meruyert100** [comment]
One octocat please 🥹

**Comment by naumiec** [comment]
🖤

**Comment by lennertderyck** [comment]
![v1lbpim76kj77pnx6582](https://github.com/GH-Event-Demos/random-name-picker/assets/37124772/0a7b8e26-6af5-4fb6-8819-28d2146adb0f)

**Comment by SaiOhran** [comment]
Always have been a cat person 🙂
❤️ octocat

**Comment by dcarmen1** [comment]
Hi Github! 😊👋

**Comment by Aswinnathan** [comment]
Hej

**Comment by dr3du4** [comment]
Have a good day <3

**Comment by noahmay** [comment]
🐙🐈

**Comment by ibarbalho** [comment]
Hey Github 🤞

**Comment by vivienhennig** [comment]
🥨

**Comment by harisc5** [comment]
See you at 15h 😄

**Comment by otherguy** [comment]
Love Github :octocat:

**Comment by kunal60** [comment]
Love GitHub and thanks for the badge and stickers 🙂

**Comment by KePeterZ** [comment]
The most unoriginal string I could think of: "Hello world!"

**Comment by thecodingcrow** [comment]
Hi friendly Bot, may I get a plushie? 🤓

**Comment by Meruyert100** [comment]
🐱

**Comment by pedrodiogo219** [comment]
Heyy

**Comment by Meruyert100** [comment]
hallo welt

**Comment by IsackHaer** [comment]
GitHub is love GitHub is life

**Comment by Meruyert100** [comment]
👯‍♀️

**Comment by Meruyert100** [comment]
🦆

**Comment by perryrh0dan** [comment]
Hi GitHub

**Comment by Meruyert100** [comment]
🌝

**Comment by Meruyert100** [comment]
💅🏻

**Comment by Meruyert100** [comment]
🌞

**Comment by lucashaertel** [comment]
Lets go github ❤️

**Comment by lajtovo** [comment]
Hello awesome people! 🫡

**Comment by Meruyert100** [comment]
🐙

**Comment by UemitCebi** [comment]
❤️ github

**Comment by Meruyert100** [comment]
🥑

**Comment by Meruyert100** [comment]
❤️‍🔥

**Comment by leichteckig** [comment]
Was wonderful to meet you in Berlin! ❤️

**Comment by efont25** [comment]
In case of fire, git push and then you can go

**Comment by MayaTzz** [comment]
Hii (:

**Comment by Kasiamusk** [comment]
Great stand in Berlin

**Comment by Malte2036** [comment]
Hello 👋

**Comment by ondrejgrof** [comment]
🇨🇿

**Comment by sarathcodes** [comment]
Hello

**Comment by speladragan** [comment]
Pick me! 🤞

**Comment by Aleksanderlebedenko** [comment]
Hello!

**Comment by s0er3n** [comment]
<3

**Comment by dom18lol** [comment]
Hello 👋

**Comment by rockyliyanlok** [comment]
Hey! Hello!

**Comment by MayaTzz** [comment]
Helloo

**Comment by ji-nan** [comment]
Hey hey

**Comment by Dominik28111** [comment]
👉👈

**Comment by ageorgijev** [comment]
Hello :-)

**Comment by leonshenprojects** [comment]
Yoyoyo

**Comment by DerIsi** [comment]
Wuhuuuu WAD Gang

**Comment by dhlavac** [comment]
Potato

**Comment by lostdesign** [comment]
good soup

**Comment by kriskbx** [comment]
👋

**Comment by pgraemer** [comment]
Hello there ☕

**Comment by DianaAngh** [comment]
Hello Git !!

**Comment by gvytenis** [comment]
Heyo!

**Comment by Tautve** [comment]
Hello! 👋

**Comment by Thyago** [comment]
Hello there

**Comment by zxpower** [comment]
Hello 😁👋🏻

**Comment by MrsNovy** [comment]
Hello😁😁👋

**Comment by nodify-at** [comment]
LGTM 🎉

**Comment by t-arenas** [comment]
Helloo 😎😎

**Comment by mancia93** [comment]
LGTM

**Comment by craftedcodes** [comment]
Octocat forever!!!

**Comment by VladGhelbere** [comment]
Hi !

**Comment by IsmaQO** [comment]
Hello there!

**Comment by ashiishme** [comment]
GitHub is awesome 😍😍😍

**Comment by vincenzosarnataro** [comment]
Hello 🤟

**Comment by lorenzofiamingo** [comment]
Go GitHub go!!!!!!!!

**Comment by fabiosassu** [comment]
Hello world!

**Comment by alessandrostuppino** [comment]
WE ARE DEVELOPERS! 👾

**Comment by wisam-alhennawi** [comment]
Hello!

**Comment by Kugellehenerin** [comment]
😍😍😍😍

**Comment by FelixMertin** [comment]
Riffle raffle gittle gattle. I wanna win 🥇

**Comment by dusandamljanovic-noumena** [comment]
w>

**Comment by wassim-henia** [comment]
Wearedeveloper2023

**Comment by BProg** [comment]
Thank you
![image](https://github.com/GH-Event-Demos/random-name-picker/assets/11962191/2606ec37-f307-41cc-98ee-bb4b58c10e4b)

**Comment by hamzaamin1** [comment]
Hola!

**Comment by bwiedmann** [comment]
Cheers!

**Comment by rw4lll** [comment]
🐙

**Comment by Siregar** [comment]
It’s soo cute! 🥰 Aaand I love your Design System. 😍

**Comment by sebil** [comment]
You guys rock! 🤘🐙

**Comment by alisen** [comment]
Hellooo 👋

**Comment by konradrenner** [comment]
Hello everybody 👋

**Comment by Nagaveena007** [comment]
I have been using GitHub since from ever 😍 i don't know what to comment
They are incredible 🤩 just keep rocking 💪

**Comment by noisymold** [comment]
Hi!

**Comment by ggarcia24** [comment]
Hello!

**Comment by ukatia** [comment]
Hello developers!

**Comment by divinedragon** [comment]
![IMG20230728132505.jpg](https://github.com/GH-Event-Demos/random-name-picker/assets/91791/0f37d9cf-c21d-406b-b124-51aad7da24ec)

Thank you

**Comment by divinedragon** [comment]
![IMG20230728132505.jpg](https://github.com/GH-Event-Demos/random-name-picker/assets/91791/0f37d9cf-c21d-406b-b124-51aad7da24ec)

Thank you

**Comment by Hooning** [comment]
Thanks for the stickers.

**Comment by MDybek** [comment]
Greetings from Poland!

**Comment by Kisiekx** [comment]
:D

**Comment by maticardenas** [comment]
Go copilot! 🤖🦾

**Comment by RazeViana** [comment]
Yoooooo

**Comment by forntoh** [comment]
I love GitHub ❤️❤️❤️

**Comment by Meruyert100** [comment]
🙂

**Comment by Meruyert100** [comment]
:)

**Comment by itsyulie94** [comment]
😍😍😍😍

**Comment by Meruyert100** [comment]
:D

**Comment by Meruyert100** [comment]
:P

**Comment by Meruyert100** [comment]
Hello from Kazakhstan

**Comment by atefth** [comment]
Halo!!!

**Comment by Meruyert100** [comment]
🤓

**Comment by Meruyert100** [comment]
🥲

**Comment by dsansyzbayev** [comment]
Waduuup?

**Comment by Meruyert100** [comment]
☺️

**Comment by Meruyert100** [comment]
🤩

**Comment by 4inodev** [comment]
Wasuuupp

**Comment by Meruyert100** [comment]
🥳

**Comment by 4inodev** [comment]
🤙

**Comment by Meruyert100** [comment]
🤠

**Comment by hila3000** [comment]
Swag FTW

**Comment by kerenk100** [comment]
AMAZING SWAG!!! 😍🤩

**Comment by nhat** [comment]
👍🏻

**Comment by Cahoo** [comment]
Hi from Ukraine!)

**Comment by flohtux** [comment]
Amazing Copilot Demo! Thanks!

**Comment by Jrrney** [comment]
Martin for the win. Love GitHub Copilot. :)

**Comment by Tryneeth** [comment]
🤜🤛

**Comment by flx-bln** [comment]
So nice people at the booth! 👌🏻

**Comment by AntonDambrouski** [comment]
I'm playing!

**Comment by eugeneborodko** [comment]
Piece of cake

**Comment by lacastar** [comment]
It was nice to see copilot chat in Hungarian!

**Comment by mrashed-dev** [comment]
Hello! Thanks for the demo of copilot at the booth -- great stuff!

**Comment by eriksven** [comment]
Thanks for the intro

**Comment by hieu-t-code** [comment]
👁️

**Comment by hieu-t-code** [comment]
I am participating :)

**Comment by hieu-t-code** [comment]
Lets try to win

**Comment by damjan-icentic** [comment]
Great work!!!

**Comment by rolandgriesser** [comment]
🥳

**Comment by T0TProduction** [comment]
Henlo 👋🏻

**Comment by Acirema** [comment]
Hi, participating :)

**Comment by klovack** [comment]
Hi, just trying my luck 😅

**Comment by MiinhD** [comment]
Hi

**Comment by edocm** [comment]
Please

**Comment by martinwoodward** [comment]
Congratulations to:

@aygulmardanova
@Inkala 
@lcorr8 

You are a winner!!!

Thanks everyone else great seeing you!!

**Comment by mathdebate09** [comment]
🌧️
