### ISSUE TITLE
GitHub Raffle at DDD Brisbane 2022 - Leave a comment to enter

### ISSUE THREAD

**Issue by mishmanners** [GH-Event-Demos/random-name-picker#5]
<p align="center">
    <img alt="Random Name Picker for Lucky Draw" src="https://user-images.githubusercontent.com/95615501/189075655-8b5c5012-1f94-4562-93c0-eaef532d2880.png" width="100" />

# Random Name Picker for GitHub prize draw at DDD Brisbane 2022!

![banner-code-graph](https://user-images.githubusercontent.com/36594527/205007944-531bd076-1b9b-4f9b-b0eb-ddf284e2d243.png)

:pray: First, huge shout-out to [@icelam](https://github.com/icelam) for a great and simple name picker we could fork and use for the GitHub booth!

:rocket: This site is deployed to GitHub Pages using GitHub Actions. The Actions workflow pulls entrants from commenters of a GitHub Issue.

:ticket: To enter the draw, add a comment at the bottom of this issue 👇 

## 🏆  The prize draw will be drawn on stage after the locknote.

[Check out the original README](https://github.com/GH-Event-Demos/random-name-picker/blob/main/README.md)

---

A couple of T&C's:

- Entry into this raffle will NOT constitute your consent to be contacted for anything else
- We will not be adding you to our marketing database (but if you want to subscribe to our newsletter, [you can do so here](https://resources.github.com/newsletter/))
- The raffle prize cannot be swapped or changed, 
- The winner of the prize at DDD Brisbane *MUST* be at the closing of the event when we draw a winner, otherwise we will redraw!

Good luck!

**Comment by simonboots** [comment]
Hello, world! :)

**Comment by wlee88** [comment]
Thanks for stickers ❤️

**Comment by rloomans** [comment]
Toast!

**Comment by lethek** [comment]
Hello!

**Comment by QuestionableChanges** [comment]
Hey!

**Comment by TheHoffXAM** [comment]
LEGO!!!

**Comment by JustinK1973** [comment]
Looking forward to some great sessions

**Comment by gitchristopher** [comment]
a comment to enter

**Comment by ianbrown78** [comment]
Gday!

**Comment by dmcgill92** [comment]
This is a comment

**Comment by optimizfx** [comment]
Stickers!

**Comment by ChamindraRaj** [comment]
Oooh... Github stickers!

**Comment by richardp-au** [comment]
// comment

**Comment by ashwini-balnaves** [comment]
Good luck everyone!

**Comment by camillars** [comment]
Hello 😊

**Comment by vui611** [comment]
gday

**Comment by dalilakatialeo** [comment]
👋🏻 Hello! 😃

**Comment by WilliamCikes** [comment]
HelloWorld.js

**Comment by russcam** [comment]
I'd love to win some Lego 🙂 thanks!

**Comment by LiliPaulucci** [comment]
Yayyyy

**Comment by CraigRice** [comment]
Hi ¯\_(͡° ͜ʖ ͡°)_/¯

**Comment by Noctis-** [comment]
Right next to the dinosaurs !!!

**Comment by wicksipedia** [comment]
It's a me... Mario! 🥸

**Comment by bel-lloyd** [comment]
DDD Le(t’s)GO!!

**Comment by azyure** [comment]
So long, and thanks for all the fish! ;)

**Comment by markotsoi** [comment]
So, can I still win if I’m not at the booth in Perth? That will be difficult at dddbne

> The winner of the prize at DDD Perth MUST be at the booth when we draw a winner, otherwise we will redraw!

**Comment by jasontaylordev** [comment]
Hey hey hey ❤️

**Comment by jacobjmarks** [comment]
Hello there 👋

**Comment by samlev** [comment]
```php
<?for(;$i++<100;)echo $i%15?$i%5?$i%3?$i:Fizz:Buzz:FizzBuzz,"
";```

**Comment by egadgetjnr** [comment]
Thanks!

**Comment by sandy-wang** [comment]
DDD is amazing, that's the first conference since I moved to Brisbane in late 2019！Wish we have more of that.

**Comment by tkapa** [comment]
Awesome stickers from GitHub :)

**Comment by anthoneyrimmer** [comment]
Great to see so many at dddbrisbane

**Comment by JQC-hash** [comment]
Thanks for the stickers! DDD

**Comment by Steve-Hun** [comment]
Love the stickers

**Comment by reverseimaku** [comment]
Woot woot

**Comment by Tim-Barton** [comment]
Go DDD Brisbane

**Comment by johnazariah** [comment]
Yay DDD Brisbane!!

**Comment by skycube** [comment]
Love the stickers ❤️

**Comment by broccolinisoup** [comment]
Hi 😍

**Comment by andrewpoxonSL** [comment]
Hello!

**Comment by amykapernick** [comment]
What's with all the ducks? 🦆

**Comment by tahleegrace** [comment]
Toast!

**Comment by tdkseraph** [comment]
Thanks for the stickers

**Comment by tofumengy** [comment]
Can i please have the artist's name? stickers are awesomee 🔥

**Comment by patrickklug** [comment]
DdDbNe - how good are the bags!

**Comment by mattaisthorpe** [comment]
Woe!

**Comment by chaitanyagurrapu** [comment]
Hi

**Comment by duaneedwards** [comment]
Thanks for the cool stickers 😀

**Comment by turtleonabike** [comment]
Yay!

**Comment by abbasmhd** [comment]
Excellent talk thanks Mish

**Comment by gobbledygooch** [comment]
Hello World

**Comment by semiautomatix** [comment]
Great to see some of the features I didn't know existed on GitHub! Eager for the project management stuff.

**Comment by Jamolo5** [comment]
Great talk Mish!

**Comment by brydeno** [comment]
So long and thanks for all the stickers

**Comment by frank-leigh** [comment]
Hi Ma!

**Comment by Turtlator** [comment]
This is a comment!

**Comment by PaulRobson** [comment]
Thanks, GitHub!

**Comment by DmitriyMaksimov** [comment]
DDD Brisbane is awesome!

**Comment by AKlaus** [comment]
Hey!

**Comment by mishmanners** [comment]
> So, can I still win if I’m not at the booth in Perth? That will be difficult at dddbne
> 
> > The winner of the prize at DDD Perth MUST be at the booth when we draw a winner, otherwise we will redraw!

Oh dang; I missed that one. Good catch. Updated now thanks to @Damovisa ❤️

**Comment by wildshane** [comment]
@mishmanners with the correction! +1

**Comment by jamesleech** [comment]
Gotta try projects

**Comment by apollo323au** [comment]
Tabs not spaces

**Comment by AngelaClarke5678** [comment]
GitHub Copilot did not write this

**Comment by optimizfx** [comment]
Factorio! Regards, RohinOn 3 Dec 2022, at 09:01, azyure ***@***.***> wrote:﻿
So long, and thanks for all the fish! ;)

**Comment by DavidTomane** [comment]
Cheers Mish 🙌

**Comment by emiaj** [comment]
Cheers DDD BNE

**Comment by Aiden0** [comment]
`hello world`

**Comment by jernejk** [comment]
Awesome stand, love the stickers. 😊

**Comment by Caroline99** [comment]
Great talk Mish!

**Comment by baron1922** [comment]
Thanks for this morning's talk.

**Comment by aminchenton** [comment]
I'm just here for the prizes.

**Comment by karm435** [comment]
Thanks for the swags and being an awesome sponsor. 🙏

**Comment by KortVea** [comment]
Nice event

**Comment by fenix2222** [comment]
Hello world

**Comment by OliverIlMagnifico** [comment]
This is very important issue!

**Comment by AbhroneelChowdhury** [comment]
Cool booth !

**Comment by Eraph** [comment]
Biscuits

**Comment by jonfraser** [comment]
Great stickers

**Comment by RaphHaddad** [comment]
````
#!/usr/bin/env python
print('Hello World!')
````

**Comment by mishmanners** [comment]
![giphy](https://user-images.githubusercontent.com/95615501/189623416-29791d30-7040-4d21-9234-30e3e5b3fa7b.gif)

✨  Thank you to everyone who dropped by our booth and entered our raffle at DDD Brisbane! ✨

Congrats to the winner!

## This issue will be closed and we look forward to seeing you next time!

_(P.S We heard that some of you got swamped with notifications! We've factored that in for next time, but here's a [handy doc](https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications) if you want to adjust your settings for the future)_
