### ISSUE TITLE
GitHub Raffle at DDD Perth! - Leave a comment to enter

### ISSUE THREAD

**Issue by Damovisa** [GH-Event-Demos/random-name-picker#52]
<p align="center">
    
![Image](https://github.com/GH-Event-Demos/random-name-picker/assets/1887732/57fef6a1-9b95-4292-8322-93f5c492051f)

# Random Name Picker for GitHub prize draw at DDD Perth!

![banner-code-graph](https://user-images.githubusercontent.com/36594527/205007944-531bd076-1b9b-4f9b-b0eb-ddf284e2d243.png)

:pray: First, huge shout-out to [@icelam](https://github.com/icelam) for a great and simple name picker we could fork and use for the GitHub booth!

:rocket: This site is deployed to GitHub Pages using GitHub Actions. The Actions workflow pulls entrants from commenters of a GitHub Issue.

:ticket: To enter the draw, add a comment at the bottom of this issue 👇 

## 🏆  The prize will be drawn in the afternoon. Exact time TBA!

[Check out the original README](https://github.com/GH-Event-Demos/random-name-picker/blob/main/README.md)

---

A couple of T&C's:

- Entry into this raffle will NOT constitute your consent to be contacted for anything else
- We will not be adding you to our marketing database (but if you want to subscribe to our newsletter, [you can do so here](https://resources.github.com/newsletter/))
- The raffle prize cannot be swapped or changed, 
- The winner of the prize at DDD Perth *MUST* be present when we draw a winner, otherwise we will redraw!

Good luck!

**Comment by lukeperson** [comment]
Swag pls 😍

**Comment by eugenemlee** [comment]
lgtm 👍

**Comment by AbundantSalmon** [comment]
Hello :)

**Comment by OzBob** [comment]
Aaaargh

**Comment by ArisaOkuyama** [comment]
Hello ❤️❤️❤️

**Comment by s1m-0n** [comment]
Swag🙏

**Comment by chongkev** [comment]
Yo

**Comment by swangleapps** [comment]
Woo!

**Comment by Shane-oo** [comment]
Hello world

**Comment by bir-d** [comment]
Hey!

**Comment by emlyn-arkahna** [comment]
Swag please

**Comment by hailanggao** [comment]
DDD！

**Comment by iriteshmishra** [comment]
Hello

**Comment by marinadelafuente** [comment]
I want this!!

**Comment by alexcollier** [comment]
DDD Perth for win

**Comment by iriteshmishra** [comment]
Hello

**Comment by karthiksalila86** [comment]
DDDperth

**Comment by JuanNavarro-DD** [comment]
Hello

**Comment by Nazareh** [comment]
I love the stickers

**Comment by Nazareh** [comment]
I love the stickers

**Comment by CodeWithTheDoctor** [comment]
We love the swagg

**Comment by MelDie** [comment]
Swag pls 🙂

**Comment by eric-winkler** [comment]
🚀

**Comment by lukedev820** [comment]
Hello world! 🐧

**Comment by UnicodeTreason** [comment]
I was here

**Comment by spyn** [comment]
Swiggity swag

**Comment by pzi** [comment]
Swag please and thank you <3

**Comment by thestillheron** [comment]
Having fun at DDD!

**Comment by JakeNHelfrich** [comment]
Hello!

**Comment by callumfrance** [comment]
LGTM, no blockers

**Comment by StephTrevi** [comment]
Hello 🤖

**Comment by EDZ-SWM** [comment]
Lgtm

**Comment by readyjune** [comment]
SWAG!!!!! DDDPERTH

**Comment by HarryWard-15** [comment]
Took my 5 minutes to remember my password

**Comment by LachlanED** [comment]
❤️ GitHub merch

**Comment by aSimpleUsername** [comment]
aSimpleComment

**Comment by frinzekt** [comment]
Wooohooo!!!

**Comment by jmberon** [comment]
Swag me up please DDD Perth!

**Comment by lesterbustamante** [comment]
great tuffs

**Comment by ramilyao** [comment]
> ![Image](https://user-images.githubusercontent.com/1887732/273350834-57fef6a1-9b95-4292-8322-93f5c492051f.png)
> 
> # Random Name Picker for GitHub prize draw at DDD Perth!
> ![banner-code-graph](https://user-images.githubusercontent.com/36594527/205007944-531bd076-1b9b-4f9b-b0eb-ddf284e2d243.png)
> 
> 🙏 First, huge shout-out to [@icelam](https://github.com/icelam) for a great and simple name picker we could fork and use for the GitHub booth!
> 
> 🚀 This site is deployed to GitHub Pages using GitHub Actions. The Actions workflow pulls entrants from commenters of a GitHub Issue.
> 
> 🎫 To enter the draw, add a comment at the bottom of this issue 👇
> 
> ## 🏆 The prize will be drawn in the afternoon. Exact time TBA!
> [Check out the original README](https://github.com/GH-Event-Demos/random-name-picker/blob/main/README.md)
> 
> A couple of T&C's:
> 
> * Entry into this raffle will NOT constitute your consent to be contacted for anything else
> * We will not be adding you to our marketing database (but if you want to subscribe to our newsletter, [you can do so here](https://resources.github.com/newsletter/))
> * The raffle prize cannot be swapped or changed,
> * The winner of the prize at DDD Perth _MUST_ be present when we draw a winner, otherwise we will redraw!
> 
> Good luck!

Swag!

**Comment by tanvig390** [comment]
💗 swag . Goo github

**Comment by Anushka144** [comment]
#DDDPerth Developer's love GitHub!

**Comment by JianzhenT** [comment]
Let's get it👀👀

**Comment by sue-lim** [comment]
Thanks guys !!!

**Comment by beremaran** [comment]
DDD!

**Comment by Vylan66** [comment]
GitHub 🥳

**Comment by letheon** [comment]
Hello from DDD Perth!

**Comment by fmg-emily** [comment]
foo

**Comment by victorolet** [comment]
Hello

**Comment by juuuuuuuuut** [comment]
What do you call a fake noodle

**Comment by Turtlator** [comment]
Hello world

**Comment by danaahm** [comment]
Use GitKraken instead of CLI 👀

**Comment by DonSharpCyber** [comment]
Best stickers every year!

**Comment by Valerietata** [comment]
Yay

**Comment by alanychan** [comment]
Thanks GitHub!!! You're amazing 🤩

**Comment by PlanitSimmo** [comment]
github for life!

**Comment by martinotaylor** [comment]
GitHub be awesome!!

**Comment by HaydenReeve** [comment]
Hello 👋

**Comment by aleishasabin** [comment]
Thanks GitHub! #DDDPerth

**Comment by brandonbarkerRAC** [comment]
🙏

**Comment by Hawxy** [comment]
👋

**Comment by mcrnbrck** [comment]
I need more DDD

**Comment by nicoletr** [comment]
Pls and thanku 🐙

**Comment by Accurate0** [comment]
🙏

**Comment by tomgarner** [comment]
Hello world

**Comment by mysticitgirl** [comment]
Yes please! Love it

**Comment by Nidz2501** [comment]
Great tuffs!

**Comment by borisbasque** [comment]
Lessgoo

**Comment by dct0** [comment]
😎

**Comment by n3ih7** [comment]
So good to be a part of today's conference. Thanks GitHub.

**Comment by Rachit-A** [comment]
Thank u

**Comment by danish3r** [comment]
Wanna win!

**Comment by InOmniaParatus-WD** [comment]
You guys rock!!👍🏼

**Comment by NickWalters** [comment]
Hello GitHub!

**Comment by FelipeVasoncelos** [comment]
💚🚀

**Comment by abriehalgryn** [comment]
Heyaaaa GitHub!!!! Ily

**Comment by JimmyStewtron** [comment]
Loving DDD 2023

**Comment by misbhven** [comment]
Copilot wrote this comment!!!

**Comment by kevle1** [comment]
git commit -m "pls"

**Comment by denzilsoans** [comment]
DDD is awesome

**Comment by awildsouffle** [comment]
Cute stickers!!

**Comment by ajitsangwan2006** [comment]
Awesome

**Comment by ivy0305** [comment]
:)

**Comment by justinliangg** [comment]
🤞

**Comment by domcain** [comment]
Please just a crumb of waterbottle

**Comment by Fil-Naj** [comment]
😋

**Comment by bido170** [comment]
> ![Image](https://user-images.githubusercontent.com/1887732/273350834-57fef6a1-9b95-4292-8322-93f5c492051f.png)
> 
> # Random Name Picker for GitHub prize draw at DDD Perth!
> ![banner-code-graph](https://user-images.githubusercontent.com/36594527/205007944-531bd076-1b9b-4f9b-b0eb-ddf284e2d243.png)
> 
> 🙏 First, huge shout-out to [@icelam](https://github.com/icelam) for a great and simple name picker we could fork and use for the GitHub booth!
> 
> 🚀 This site is deployed to GitHub Pages using GitHub Actions. The Actions workflow pulls entrants from commenters of a GitHub Issue.
> 
> 🎫 To enter the draw, add a comment at the bottom of this issue 👇
> 
> ## 🏆 The prize will be drawn in the afternoon. Exact time TBA!
> [Check out the original README](https://github.com/GH-Event-Demos/random-name-picker/blob/main/README.md)
> 
> A couple of T&C's:
> 
> * Entry into this raffle will NOT constitute your consent to be contacted for anything else
> * We will not be adding you to our marketing database (but if you want to subscribe to our newsletter, [you can do so here](https://resources.github.com/newsletter/))
> * The raffle prize cannot be swapped or changed,
> * The winner of the prize at DDD Perth _MUST_ be present when we draw a winner, otherwise we will redraw!
> 
> Good luck!

Love the stickers 🐈‍⬛
![image](https://github.com/GH-Event-Demos/random-name-picker/assets/147222441/7b723012-ac96-431e-9e32-b771a3633318)
![image](https://github.com/GH-Event-Demos/random-name-picker/assets/147222441/f26c44e0-5ef8-4ff1-9829-ec516a529a13)
![image](https://github.com/GH-Event-Demos/random-name-picker/assets/147222441/8efd3f6a-9b09-433d-8375-f4aa99ce559b)
![image](https://github.com/GH-Event-Demos/random-name-picker/assets/147222441/8f0d0047-ccba-47df-a16b-00a0f4460bc2)

**Comment by ASherry114** [comment]
CoPilot is incredibly powerful, so much so that I have considered moving my tab key to the middle of my keyboard as it is now my most used key

**Comment by manthaphanindra** [comment]
Hello .. 🤩

**Comment by anthonykusuma** [comment]
That water bottle looks cool!

**Comment by cyb3rturnip** [comment]
Nice stand and love the stickers!

**Comment by antonjb** [comment]
:shipit:

**Comment by MichaelLivens** [comment]
Go me!

**Comment by Rhyz-jpg** [comment]
Copilot Rulz

**Comment by mir0slav1** [comment]
Swag plzzz ❤️❤️

**Comment by AatishP** [comment]
Hello!

**Comment by mariapetra** [comment]
Hey!

**Comment by jayde3m** [comment]
Actions4Life

**Comment by Ms-KL** [comment]
OctoKitty 4 life🐱🐙

**Comment by Melski21** [comment]
Hi there

**Comment by RaspreetK** [comment]
Cool swag please!

**Comment by DeepiMati** [comment]
Hi

**Comment by TitanCmd** [comment]
🙏

**Comment by dev-fJ-del** [comment]
🤙

**Comment by OldRustyDijkstra** [comment]
LGTM - pass the bat

**Comment by playitsafe** [comment]
github is awesome

**Comment by Veryinheart** [comment]
Swag 😎

**Comment by kcOpenspace** [comment]
Ken thinks GitHub stickers rock !!

**Comment by 23992836** [comment]
👍🏻👍🏻👍🏻

**Comment by bencart** [comment]
🚀

**Comment by yunho7687** [comment]
Ohh!

**Comment by bibyen** [comment]
🐸

**Comment by muswain** [comment]
Nice

**Comment by quaz4** [comment]
Hello world

**Comment by johnathanl** [comment]
Thank you for sponsoring the event!

**Comment by dylanwatsonsoftware** [comment]
All the swag pls!

**Comment by HilaryCodeLab** [comment]
Hi there!

**Comment by charlieSewell** [comment]
Hello

**Comment by thumindu007** [comment]
Helo

**Comment by Alkanoidwastaken** [comment]
Thanks Github for sponsoring the event. You guys are also really useful

**Comment by Alecadabra** [comment]
👻

**Comment by muswain** [comment]
Hello

**Comment by jessbudd** [comment]
Swag please ♥️

**Comment by Blimy** [comment]
Swag 🥰🦄🌈🌈🌈

**Comment by NicholasChoong** [comment]
Amazing

**Comment by binarysquid** [comment]
Quacky!

**Comment by xyloponion** [comment]
Yay for GitHub

**Comment by IsaaacLim** [comment]
DDDaniel! Thanks for accepting my feedback on Github for students 🧑‍🎓

**Comment by scrtsrc** [comment]
yay ddd 2023!

**Comment by filperthian** [comment]
DDDay 2023!

**Comment by emihardej** [comment]
Live love github

**Comment by yahuio** [comment]
yo DDD

**Comment by PascalSun** [comment]
I am luck

**Comment by HannahLZY** [comment]
DDDDDDD!

**Comment by anilkhadka2023** [comment]
Great talks

**Comment by cyrilgagnaire** [comment]
Love your stand at #dddperth

**Comment by DatNgo-dev** [comment]
@DDD2023 whoop

**Comment by robashcroft-rac** [comment]
Hello from DDD Perth. I love free swag! :-)

**Comment by BunningsWarehouseOfficial** [comment]
Hello!

**Comment by daniel-sheward** [comment]
...

**Comment by gibbage** [comment]
I ♥️ swag!

**Comment by rapplatt** [comment]
Hello!

**Comment by mephysto** [comment]
Love me some swag ;)

**Comment by seanmolam** [comment]
Yes please!

**Comment by milesflavel** [comment]
praise: good sticker selection at the booth

**Comment by Mause** [comment]
Heya!

**Comment by eloise-c** [comment]
Thank you legends!

**Comment by KayeDante89** [comment]
Swagginggg

**Comment by elliz** [comment]
Swagalicious

**Comment by wingylui** [comment]
Hi :)

**Comment by queena25** [comment]
😊

**Comment by komaldevgun** [comment]
🙂

**Comment by ykristine13** [comment]
Hi Github team! Love your booth at DDD Perth 2023 ❤️

**Comment by fullmetalsheep** [comment]
Just here for the free stuff 😭😂

**Comment by ebloom19** [comment]
Awesome booth #dddperth

**Comment by thaingu** [comment]
Bello

**Comment by YauGoh** [comment]
Hi

**Comment by bplowry** [comment]
Hello, gimme stickers

**Comment by egaspar0** [comment]
Stickers galore

**Comment by NasehR** [comment]
🙂

**Comment by FizzBuzz791** [comment]
Love GitHub Actions! #dddperth

**Comment by rubal0494** [comment]
Best stickers!!!

**Comment by tofumengy** [comment]
Hi there!

**Comment by bencurrandev** [comment]
GitHub is awesome! ❤️ #dddperth

**Comment by GraceMeng93** [comment]
Lucky lucky girl

**Comment by MichaelThomasMPT** [comment]
Count me in please!

**Comment by Lozfizzle** [comment]
🔥🔥🔥

**Comment by nicholls73** [comment]
Github

**Comment by ReticentRex** [comment]
Beast

**Comment by dylanwatsonsoftware** [comment]
Very cool

**Comment by dylanwatsonsoftware** [comment]
Much excite

**Comment by kateraynesgoldie** [comment]
Space is cool

**Comment by MattUpnext** [comment]
Great drink bottle

**Comment by LacHex** [comment]
Thanks for the stickers! ❤️‍🔥

**Comment by SebHex** [comment]
Thanks for the stickers 😁 
![2023-10-07-15-18-48-836](https://github.com/GH-Event-Demos/random-name-picker/assets/86801115/98372763-7477-4143-9f54-b1bff7280e94)

**Comment by Grae-Saunders** [comment]
Hi

**Comment by termita81** [comment]
YOLO

**Comment by ArcticGizmo** [comment]
Comment

**Comment by mishmanners** [comment]
Congrats to all the winners, and thanks everyone for visiting our booth.
