### ISSUE TITLE
GitHub Raffle at AWS re:Invent Day 2 (11/29) - Leave a comment to enter

### ISSUE THREAD

**Issue by alexandradonlin** [GH-Event-Demos/random-name-picker#57]
![Image](https://github.com/GH-Event-Demos/random-name-picker/assets/97047475/c6ea81c4-a008-4ec1-924c-1400576a9bec)

# Random Name Picker for GitHub prize draw at AWS re:Invent Day 2!

![banner-code-graph](https://user-images.githubusercontent.com/36594527/205007944-531bd076-1b9b-4f9b-b0eb-ddf284e2d243.png)

:pray: First, huge shout-out to [@icelam](https://github.com/icelam) for a great and simple name picker we could fork and use for the GitHub booth!

:rocket: This site is deployed to GitHub Pages using GitHub Actions. The Actions workflow pulls entrants from commenters of a GitHub Issue.

:ticket: To enter the draw, add a comment at the bottom of this issue 👇 

## 🏆  The prize will be drawn on 11/29 at 4pm

[Check out the original README](https://github.com/GH-Event-Demos/random-name-picker/blob/main/README.md)

---

A couple of T&C's:

- Entry into this raffle will NOT constitute your consent to be contacted for anything else
- We will not be adding you to our marketing database (but if you want to subscribe to our newsletter, [you can do so here](https://resources.github.com/newsletter/))
- The raffle prize cannot be swapped or changed, 
- The winner of the prize at AWS re:Invent Day 2 *MUST* come back to the booth after they are notified they have won to claim their prize, otherwise we will redraw!

Good luck!

**Comment by cnelissen** [comment]
I like shoes.

**Comment by stephen-mogensen** [comment]
Github rocks!

**Comment by paulpapas123** [comment]
Githubs awesome and i want it on my shoes

**Comment by cookapps-jhlee11** [comment]
I like shoes

**Comment by HaganMcPhail** [comment]
Kyle's GitHub presentation today was 👍

**Comment by vortexzn** [comment]
GitHub rocks

**Comment by jmeyer42** [comment]
Hooray, shoes! Thanks for the stickers!

**Comment by tonyrbf96** [comment]
Go go GitHub!

**Comment by ultraschuppi** [comment]
I like shoes

**Comment by ColRad** [comment]
Love the Octocat!

**Comment by urbanisierung** [comment]
I like shoes

**Comment by chris-kck** [comment]
re:Invent 🤟🏾

**Comment by RogerDavidCruz** [comment]
For the swagggg

**Comment by d-hong** [comment]
GitHub Converse Swag! Lets go!

**Comment by OlaShabalina** [comment]
GitHub is the best!

**Comment by wosti** [comment]
Git Hub  wow😍😍😍

**Comment by rupesh-khandwe** [comment]
GitHub rocks!!

**Comment by jatinmehrotra** [comment]
re:hub 2023 👉🏻👈🏻

**Comment by rajholla** [comment]
Hello GitHub 🙏

**Comment by g-linville** [comment]
Howdy

**Comment by jasmin-alvarez** [comment]
![image](https://github.com/GH-Event-Demos/random-name-picker/assets/70730021/5eb7043c-bff8-4411-a6b9-d20930ad6185)

GitHub rules 🥹❤️

**Comment by elvis-mofor** [comment]
Love how GitHub is the single tool my entire company uses

**Comment by allenahner** [comment]
🙌 for copilot cli

**Comment by Marianalima31** [comment]
I love to use github and aws ❤️ this collab is amazing. Give me the shoes 🥹

**Comment by rodrigo-abrantes** [comment]
S2 git hub 🤯🤯

**Comment by koinhoon** [comment]
Hello👋 github

**Comment by diminako** [comment]
The best booth at AWS by far :)

**Comment by ailen0ada** [comment]
shoes!!!

**Comment by Izanagi95** [comment]
Hope

**Comment by steve0hh** [comment]
For the swagggg

**Comment by abhisheksn** [comment]
Will commit for shoes

**Comment by saif-software-developer** [comment]
GitHub for life

**Comment by sharma21069** [comment]
Nice 👍

**Comment by deviantant** [comment]
Go github, love copilot!

**Comment by natedawg0921** [comment]
I need shoes

**Comment by MattMyers3** [comment]
Hello friends!

**Comment by Latllatl** [comment]
I need these shoes 😂😂

**Comment by ricardorames** [comment]
I wanna it! ❤️

**Comment by WilliamJohns** [comment]
👟🎟️

**Comment by chadwickidy** [comment]
Glad to be here!

**Comment by nicoangel08** [comment]
Good luck

**Comment by fahad-tariq** [comment]
Let’s go!

**Comment by MPOgbourne** [comment]
I need these.

**Comment by mcwagner** [comment]
My shoes are getting worn with all this walking.

**Comment by jageek** [comment]
Pick me!!!

**Comment by GiselleSerate** [comment]
hello!

**Comment by svc333** [comment]
Hey

**Comment by SacredWizard** [comment]
Wohoo!! Copilot 🐱✈️

**Comment by bpoetzschke** [comment]
I like shoes.

**Comment by nozo-moto** [comment]
I like shoes.

**Comment by genedragon** [comment]
Gotta have the Converse!

**Comment by tarao1006** [comment]
I like shoes.

**Comment by robydrupo** [comment]
I am barefoot please help.

**Comment by robbintt** [comment]
I would love these for the gym -- squats and deadlifts!

**Comment by ByFinni** [comment]
Some shoes please :)

**Comment by creil94** [comment]
Hi from reinvent :)

**Comment by vishm01** [comment]
Copilot for the win!

**Comment by mingzheng168** [comment]
Love GitHub

**Comment by davidkshepherd** [comment]
Pick me! 

And check out http://reInventParties.com

**Comment by BlackDark** [comment]
Comment :)

**Comment by linkvt** [comment]
🐙🐱

**Comment by michaelmagreola** [comment]
Awesome. I love Github!

**Comment by Bardiel03** [comment]
😬

**Comment by ghost1face** [comment]
Pick me!!

**Comment by Danylevy** [comment]
I'll take those shoes 😁

**Comment by abramverseio** [comment]
Shoes please

**Comment by shiestyle** [comment]
Thanks!

**Comment by satish83brea** [comment]
GitHub is Amazing

**Comment by SKChristopher** [comment]
🥹

**Comment by chewingthebars** [comment]
Yo!

**Comment by isaiah4115** [comment]
Checking in

**Comment by bravebright** [comment]
I❤️GH

**Comment by belindadunu** [comment]
Pick me :)

**Comment by hongshuo-zhang** [comment]
jsjajajaanana

**Comment by jcfg123** [comment]
❤️

**Comment by JordanWells** [comment]
pls gimme shoe

**Comment by alexandradonlin** [comment]
@stephen-mogensen @jasmin-alvarez @genedragon @rajholla @fahad-tariq @ricardorames @prateekpatil @jageek @pedropnaves @n2zz @michaelmagreola @urbanisierung @bpoetzschke @ailen0ada @rupesh-khandwe @jcfg123 @GiselleSerate @satish83brea @MattMyers3 @tarao1006 CONGRATS!!! You are the winners of the GitHub Converse shoes on day 2 (11/29) of AWS re:Invent. To claim your prize, please come back to the GitHub booth (1196) by 12pm on Thursday. Thank you!
