### ISSUE TITLE
GitHub Raffle at GitHub + Vercel AI Strikes at AWS re:Invent - Leave a comment to enter

### ISSUE THREAD

**Issue by alexandradonlin** [GH-Event-Demos/random-name-picker#58]
![Image](https://github.com/GH-Event-Demos/random-name-picker/assets/97047475/64a2a3f3-13e2-48ed-a004-329b43800e41)

# Random Name Picker for GitHub prize draw at the AI Strikes reception at AWS re:Invent!

![banner-code-graph](https://user-images.githubusercontent.com/36594527/205007944-531bd076-1b9b-4f9b-b0eb-ddf284e2d243.png)

:pray: First, huge shout-out to [@icelam](https://github.com/icelam) for a great and simple name picker we could fork and use for the GitHub booth!

:rocket: This site is deployed to GitHub Pages using GitHub Actions. The Actions workflow pulls entrants from commenters of a GitHub Issue.

:ticket: To enter the draw, add a comment at the bottom of this issue 👇 

## 🏆  The prize will be drawn toward the end of the event on 11/28

[Check out the original README](https://github.com/GH-Event-Demos/random-name-picker/blob/main/README.md)

---

A couple of T&C's:

- Entry into this raffle will NOT constitute your consent to be contacted for anything else
- We will not be adding you to our marketing database (but if you want to subscribe to our newsletter, [you can do so here](https://resources.github.com/newsletter/))
- The raffle prize cannot be swapped or changed, 
- The winner of the prize at the AI Strikes reception at AWS re:Invent *MUST* be present at the time of drawing to claim their prize, otherwise we will redraw!

Good luck!

**Comment by yongjip** [comment]
Techtaka

**Comment by snewman1977** [comment]
GitHub is outstanding

**Comment by mishmanners** [comment]
Keep them coming people, you're all in the draw!

**Comment by judisyau** [comment]
GitHub is great!!!

**Comment by Antoniorios17** [comment]
Let's go github

**Comment by alainajaffer** [comment]
Github is cool

**Comment by canzhen** [comment]
give me the shoe pleeeeeeeaaase

**Comment by josephyi** [comment]
Thx for the fun event!

**Comment by snewman1977** [comment]
Awesome sneakers!

**Comment by mariolpgz** [comment]
Good times!

**Comment by Amal-David** [comment]
Lfg github

**Comment by alexandradonlin** [comment]
@mariolpgz @snewman1977 @josephyi @canzhen @alainajaffer @Antoniorios17 @judisyau @yongjip @Amal-David @adrika912 CONGRATS!!! You are the winners of the custom GitHub Converse sneakers and bowling shirt from the AI Strikes bowling reception on 11/28. If you are still at Brooklyn Bowl, please come to the hostess stand to get your shirt and so we can collect your info for the shoes. If you are not, please visit the GitHub booth during AWS re:Invent (1196) before Thursday at 12pm to collect your prizes.

**Comment by jay-borkar** [comment]
Sneakers please
