### ISSUE TITLE
GitHub Raffle at OSF 2-23 Infobip Shift Miami 2024 Ticket giveaway.

### ISSUE THREAD

**Issue by AndreaGriffiths11** [GH-Event-Demos/random-name-picker#62]
# Win a Ticket to [Infobip Shift Miami 2024!](https://shift.infobip.com/us/) 🎟️

<img src="https://github.com/GH-Event-Demos/random-name-picker/assets/20666190/839e1d87-9eae-48bf-bfbd-c849bdc8634d" width="500">

🎫 Here's how to enter: Simply leave a comment on this issue below 👇. Please don't start a new issue to enter.

## 🏆 Prize Draw Announcement

**Join us at the end of [Friday's stream with Kojo Idrissa](https://studio.youtube.com/video/zSaX502rVkc) for the prize draw! Don't miss out on your chance to win.**

[Explore the original README for more details on this app](https://github.com/GH-Event-Demos/random-name-picker/blob/main/README.md)

---

### Terms & Conditions:

- Make sure you're available to attend [Infobip Shift Miami](https://shift.infobip.com/us/). The prize—a Regular Pass General valued at $369.94—is strictly non-transferable, non-exchangeable, and cannot be redeemed for cash.
- Entering the raffle does not opt you into any further communications.
- We won't add you to our marketing database without your permission, but if you're interested in staying in the loop, [subscribe to our newsletter here](https://resources.github.com/newsletter/).
- The prize is as stated: No substitutions or changes allowed.

Wishing you all the best of luck! Let the excitement begin! 🍀

**Comment by Eggie09** [comment]
Hi, Best of luck to everyone. Especially to me.

**Comment by antonio-pedro99** [comment]
Best Lucky

**Comment by JaviTrek** [comment]
Crossing my fingers lol?

**Comment by AndreaGriffiths11** [comment]
Congratulations @JaviTrek

![Image](https://github.com/GH-Event-Demos/random-name-picker/assets/20666190/5aee4d52-90a4-4a29-a541-06c129440312)

Please email me at andreagriffiths11@github.com or DM alacolombiadev in X
