### ISSUE TITLE
GitHub Raffle at Open Source Summit North America 2024 - Leave a comment to enter

### ISSUE THREAD

**Issue by karasowles** [GH-Event-Demos/random-name-picker#64]
<p align="center">
    <img alt="Random Name Picker for Lucky Draw" src="https://user-images.githubusercontent.com/95615501/189075655-8b5c5012-1f94-4562-93c0-eaef532d2880.png" width="100" />

# GitHub prize draw & trivia at Open Source Summit North America 2024!

![banner-code-graph](https://user-images.githubusercontent.com/36594527/205007944-531bd076-1b9b-4f9b-b0eb-ddf284e2d243.png)

:pray: First, huge shout-out to [@icelam](https://github.com/icelam) for a great and simple name picker we could fork and use for the GitHub booth!

:rocket: This site is deployed to GitHub Pages using GitHub Actions. The Actions workflow pulls entrants from commenters of a GitHub Issue.

:ticket: To enter the draw, add a comment at the bottom of this issue 👇 

## 🏆  The prize will be drawn at **3PM each day** of Open Source Summit, at the GitHub Booth!

We'll be doing trivia at the raffle drawing - come show off your GitHub knowledge!

[Check out the original README](https://github.com/GH-Event-Demos/random-name-picker/blob/main/README.md)

---

A couple of T&C's:

- Entry into this raffle will NOT constitute your consent to be contacted for anything else
- We will not be adding you to our marketing database (but if you want to subscribe to our newsletter, [you can do so here](https://resources.github.com/newsletter/))
- The raffle prize cannot be swapped or changed, 
- The winner of the prize at Open Source Summit NA *MUST* be present when we draw a winner, otherwise we will redraw!

Good luck!

**Comment by lrusak** [comment]
GitHub is awesome!

**Comment by XenuIsWatching** [comment]
GitHub is the greatest!

**Comment by akshaaatt** [comment]
The GitHub team made me do it :)

**Comment by anubhav06** [comment]
Hello

**Comment by JamieMagee** [comment]
Hello world :fishsticks:

**Comment by craftypenguins-chris** [comment]
Best selection of stickers ever!

**Comment by dcorbeil** [comment]
I love GitHub!

**Comment by varayal** [comment]
Cool stickers :)

**Comment by flyingbusch** [comment]
Yay GitHub!!

**Comment by rithindattag** [comment]
open source 🔥

**Comment by juanis2112** [comment]
🧡🧡

**Comment by jprvita** [comment]
😸

**Comment by kendrickhang** [comment]
Thanks for the fantastic sessions today! So great to meet y’all at your table too.

**Comment by jonathandieu** [comment]
Comment 🥴

**Comment by ajbozarth** [comment]
OSS GitHub!

**Comment by jeffWelling** [comment]
Sticker game is on point!

**Comment by JDuchniewicz** [comment]
Go Go OS ♥️

**Comment by spencerschrock** [comment]
:octocat: stickers galore

**Comment by kathyon** [comment]
Got stickers!

**Comment by hnben** [comment]
Thanks for the talk! Had a great time so far at OS!!

**Comment by oliverchang** [comment]
Hi

**Comment by william-castillo-jr** [comment]
Loved the "Embracing AI in Education" discussion! Thanks for all of the great info.

**Comment by mihaimaruseac** [comment]
GitHub is awesome and the engine behind OSS

**Comment by rjtrenchard** [comment]
Hello from OSS!

**Comment by nonik0** [comment]
I was here.

**Comment by mattgogerly** [comment]
Hi from OSS NA!

**Comment by AnaMMedina21** [comment]
👋🏽 ✨

**Comment by avillela** [comment]
GitHub 🩷🩷🩷

**Comment by bnb** [comment]
blorp

**Comment by karasowles** [comment]
Raffle at 3pm at the GitHub booth! See you soon!

**Comment by amanvars** [comment]
😁😁

**Comment by TanyaStere42** [comment]
Exceptional stickers!

**Comment by brandtkeller** [comment]
Entering!

**Comment by varayal** [comment]
:)

**Comment by oohwooh** [comment]
Hi :)

**Comment by rakeshutekar1** [comment]
Hello! GitHub

**Comment by threexc** [comment]
Thanks for the drinks!

**Comment by swainn** [comment]
Happy to see you at OSS!

**Comment by ashwinexe** [comment]
This is Jessica Tegner!

**Comment by evgeniy-paltsev** [comment]
More code!

**Comment by HyeongJinKim92** [comment]
For raffle! I love github!

**Comment by hui-zheng** [comment]
I am at OSS summit with GitHub

**Comment by jpreynat** [comment]
Thanks for the stickers and for being GitHub! 😊

**Comment by t1m0thyj** [comment]
GitHub and open source are awesome 😎

**Comment by zFernand0** [comment]
Hey, I'm with GitHub at the OSS NA!

**Comment by varayal** [comment]
:)

**Comment by jonathandieu** [comment]
Day 3!!!

**Comment by roshanvkhatri** [comment]
Day 3 GitHub is Awesome

**Comment by prashanttct07** [comment]
Awesome event...

**Comment by savannahostrowski** [comment]
Yay GITHUB!

**Comment by AndreaGriffiths11** [comment]
testing

**Comment by AndreaGriffiths11** [comment]
testing

**Comment by mihaimaruseac** [comment]
OSS NA was on April though...
