### ISSUE TITLE
GitHub Raffle at Techorama 2024 Belgium - Leave a comment to enter

### ISSUE THREAD

**Issue by octobrian** [GH-Event-Demos/random-name-picker#65]
<p align="center">
    <img alt="Random Name Picker for Lucky Draw" src="https://user-images.githubusercontent.com/95615501/189075655-8b5c5012-1f94-4562-93c0-eaef532d2880.png" width="100" />

# Random Name Picker for GitHub prize draw at Techorama 2024 Belgium!

![banner-code-graph](https://user-images.githubusercontent.com/36594527/205007944-531bd076-1b9b-4f9b-b0eb-ddf284e2d243.png)

:pray: First, huge shout-out to [@icelam](https://github.com/icelam) for a great and simple name picker we could fork and use for the GitHub booth!

:rocket: This site is deployed to GitHub Pages using GitHub Actions. The Actions workflow pulls entrants from commenters of a GitHub Issue.

:ticket: To enter the draw, add a comment at the bottom of this issue 👇 

## 🏆  The prize will be drawn on May 8, 2024, @ 15:40 (3:40pm)

[Check out the original README](https://github.com/GH-Event-Demos/random-name-picker/blob/main/README.md)

---

A couple of T&C's:

- Entry into this raffle will NOT constitute your consent to be contacted for anything else
- We will not be adding you to our marketing database (but if you want to subscribe to our newsletter, [you can do so here](https://resources.github.com/newsletter/))
- The raffle prize cannot be swapped or changed, 
- The winner of the prize at Techorama 2024 Belgium *MUST* be present when we draw a winner, otherwise we will redraw!

Good luck!

**Comment by colindembovsky** [comment]
Testing! I'm a Hubber so don't give me the prize 😸

**Comment by octobrian** [comment]
Testing! I can't win since I'm running the raffle!

**Comment by cheesebridge** [comment]
Ready to win!

**Comment by wolfvandenbussche** [comment]
HUGEEE W

**Comment by Verthosa** [comment]
Pleaaasseee

**Comment by MrTheremy** [comment]
Hello 🤗

**Comment by lorismingolla** [comment]
🦝

**Comment by timdhaeyer** [comment]
I want to win!

**Comment by jonathanva** [comment]
🙏🏻🙏🏻

**Comment by katje3009** [comment]
Nice 2 be here! 🥰

**Comment by Narvarthus** [comment]
👀❤️

**Comment by JeffreyRosselle** [comment]
Lets win this 😁

**Comment by RaulSebastian** [comment]
lets go

**Comment by LorenzDacx** [comment]
Fingers crossed 🤞

**Comment by wardbeyens** [comment]
As always, awesome stickers

**Comment by bdestercke** [comment]
Hi

**Comment by Kwasi2000** [comment]
🕶️

**Comment by WouterBau** [comment]
It's so fluffy!!

**Comment by PhbsSmn** [comment]
May the Force be with me

**Comment by boneste** [comment]
Techorama 2024!

**Comment by andrekiba** [comment]
ciao Techorama24!!

**Comment by CommCody** [comment]
Hi

**Comment by abernaer** [comment]
Hoping tot win!

**Comment by NickAusloos569** [comment]
Techorama is fun!

**Comment by mmphs** [comment]
Fingers crossed! 🤞🏻

**Comment by HanneCroonen** [comment]
Thumbs are up 🍀🍀🍀

**Comment by DPoortmans** [comment]
👀

**Comment by dvdstelt** [comment]
Awesome idea. What's the price? ;-)

**Comment by smholvoet** [comment]
🚀

**Comment by jplet397** [comment]
Hello

**Comment by casrou** [comment]
Casper

**Comment by rajbos** [comment]
Here!

**Comment by KoenWellekens** [comment]
Hello from techorama

**Comment by arjanvanbekkum** [comment]
Hello 😎

**Comment by BramHoubraken** [comment]
I want to win!!!!

**Comment by ThomasRoose1982** [comment]
Hope I win

**Comment by mona** [comment]
Hello from Brian

**Comment by celineostijn** [comment]
Yay 😍

**Comment by Hanh-Pham** [comment]
Let's go

**Comment by flamingbug** [comment]
Ceci n’est pas un comment

**Comment by MDONNAY** [comment]
🤞🏻 fingers crossed, 🍀

**Comment by tvanneuville** [comment]
Hoping to win the raffle!!

**Comment by kepar** [comment]
Win win win

**Comment by KennethJaques** [comment]
Yes, please

**Comment by CedricVD** [comment]
Hello!

**Comment by DarwinAnim8or** [comment]
GitHub yipeee c:

**Comment by marnixdecloedt** [comment]
Hi. Gratis booth at techorama.

**Comment by Tim-Maes** [comment]
Viva GitHub!

**Comment by RaulSebastian** [comment]
can we double our chances by commenting multiple times?

**Comment by Wolfgang-Lorenz-Codes** [comment]
Hello from Techorama

**Comment by SvenWynants** [comment]
Going for the win @ Techorama

**Comment by stevenvanloon** [comment]
🎉

**Comment by ElkeHuygen** [comment]
😁

**Comment by LarmuseauNiels** [comment]
🎉

**Comment by JeroenDeMeyer** [comment]
nice talk

**Comment by marcselis** [comment]
It would be a first if I'd win🙏

**Comment by woeterman94** [comment]
I love GitHub 😋🤩

**Comment by Ronan-code** [comment]
Love github

**Comment by janverley** [comment]
😬

**Comment by octobrian** [comment]
Thanks everyone for a great show! Hope to see you next year!
