### ISSUE TITLE
State of Open Con 2023

### ISSUE THREAD

**Issue by martinwoodward** [GH-Event-Demos/random-name-picker#7]
<p align="center">
    <img alt="Random Name Picker for Lucky Draw" src="https://user-images.githubusercontent.com/856858/217031399-90e9f60b-9659-44a2-b9bb-44925b69bdef.png" width="400" />
</p>

## GitHub prize draw at State of Open Con 2023!

:ticket: To enter the draw, add a comment at the bottom of this issue 👇 

### 🏆  The prize draw will be drawn at the GitHub Table at approximately 15:15 on Wed Feb 8th
(assuming sessions are still running on time!)

A couple of T&C's:

- Entry into this raffle will NOT constitute your consent to be contacted for anything else
- We will not be adding you to our marketing database (but if you want to subscribe to our newsletter, [you can do so here](https://resources.github.com/newsletter/))
- The raffle prize cannot be swapped or changed, 
- The winner of the prizes at SDCon 2023 *MUST* be at the closing of the event when we draw the winners, otherwise we will redraw!

:rocket: This site is deployed to GitHub Pages using GitHub Actions. The Actions workflow pulls entrants from commenters of a GitHub Issue.

Good luck and comment below to enter the draw 👇

**Comment by mcleo-d** [comment]
Hello GitHub!

**Comment by danuw** [comment]
Love the LED logo - nice to meet you Martin!

**Comment by lotfi256** [comment]
Hello World!

**Comment by arfon** [comment]
Hey GitHub!

**Comment by marnovandermaas** [comment]
I admire your badge!

**Comment by jacobbieker** [comment]
Hi!

**Comment by Cheukting** [comment]
I ❤️ GitHub… wish to have the light 💡

**Comment by mikerossiter** [comment]
Nice to meet you and thanks for the gopher badge!

**Comment by alpsden** [comment]
Nice to meet you! Thanks for the pin badge!

**Comment by Rooster212** [comment]
Hello!

**Comment by ATHENESC** [comment]
Great display!

**Comment by samswag** [comment]
Samson here and live, and I am excited

**Comment by edithturn** [comment]
Hello GitHub 🤗🥳🤩

**Comment by Revana-Siddesh-Bathi** [comment]
Hello GitHub.! Nice to meet you all!

**Comment by Santosh-Kumar-Perumal** [comment]
Hell nice to meet this is Santosh
±44 7417435331

**Comment by timclifford** [comment]
Hi 👋

**Comment by NelsonGeeko** [comment]
Hi GitHub!!

**Comment by abdullahgarcia** [comment]
¡Hola GitHub!

**Comment by t3chguy** [comment]
Hi from state of open con!

**Comment by Sophieplcnd** [comment]
thank you for the stickers 🫶

**Comment by Frankyamoah** [comment]
> <img alt="Random Name Picker for Lucky Draw" width="400" src="https://user-images.githubusercontent.com/856858/217031399-90e9f60b-9659-44a2-b9bb-44925b69bdef.png">
> 
> ## GitHub prize draw at State of Open Con 2023!
> 🎫 To enter the draw, add a comment at the bottom of this issue 👇
> 
> ### 🏆 The prize draw will be drawn at the GitHub Table at approximately 15:15 on Wed Feb 8th
> (assuming sessions are still running on time!)
> 
> A couple of T&C's:
> 
> * Entry into this raffle will NOT constitute your consent to be contacted for anything else
> * We will not be adding you to our marketing database (but if you want to subscribe to our newsletter, [you can do so here](https://resources.github.com/newsletter/))
> * The raffle prize cannot be swapped or changed,
> * The winner of the prizes at SDCon 2023 _MUST_ be at the closing of the event when we draw the winners, otherwise we will redraw!
> 
> 🚀 This site is deployed to GitHub Pages using GitHub Actions. The Actions workflow pulls entrants from commenters of a GitHub Issue.
> 
> Good luck and comment below to enter the draw 👇

Thanks for the stickers 🙏🏿

**Comment by amin-farjadi** [comment]
Thanks for the stickers 🙏🏻

**Comment by Alpahnumeric** [comment]
Hello World! Well, GitHub :)

**Comment by charhcodes** [comment]
hey, was nice talking to you today, thanks for the pins + stickers!

**Comment by outdooracorn** [comment]
Developer I am!

**Comment by lewisalexwalker** [comment]
😁😁😁😁😁

**Comment by igmitchell** [comment]
Cool to see who is working in real time

**Comment by upodroid** [comment]
Thanks for stickers.

**Comment by JDuchniewicz** [comment]
Hello there

**Comment by spiddacino** [comment]
Awesome!

**Comment by insysion** [comment]
Hey folks!

**Comment by dpgao** [comment]
Hello World!

**Comment by anirban1c** [comment]
Fab !

**Comment by brianlinuxing** [comment]
Great seeing the GitHub team today, and their book advice was very helpful!

**Comment by kirederik** [comment]
Hello! Best stickers by far!

**Comment by DamienLasseur** [comment]
print("Hello, world!")

**Comment by babolivier** [comment]
Hello 👋

**Comment by abangser** [comment]
👋 nice to see you here GH!

**Comment by salaboy** [comment]
hi github! my old friend!

**Comment by innlouvate** [comment]
Nice to meet you folks, love the data stream!

**Comment by ciisiq** [comment]
Thank you for the stickers, they look amazing also thank you for your harder work guys. 💪🏻🙌🏻

**Comment by guythomson** [comment]
Build broke!

Thanks for the stickers 😀

**Comment by javixeneize** [comment]
🤙🤙

**Comment by mjm0** [comment]
Having a blast today! 😊

**Comment by ethomson** [comment]
Great to see you, @martinwoodward!

**Comment by dcowan-london** [comment]
Hi, GitHub!

**Comment by mehakkak** [comment]
Great product

**Comment by megarratt13** [comment]
Loving GitHub at SOOCon23. Martin Woodward has been exceptional.

**Comment by goobric** [comment]
GitHub always keeps the community Open Source and collaborative

**Comment by lcrilly** [comment]
Swag 👕🤠 FTW!

**Comment by jrsouth** [comment]
Hello GitHub 👋

**Comment by Kirol54** [comment]
Hello world!

**Comment by JonTheNiceGuy** [comment]
Gotta be in it to win it!

**Comment by Sunbearian** [comment]
Loved the data visualisation showing all the activity globally on GitHub!

**Comment by akrabat** [comment]
Hey! I’m having a great SOOCon23!

**Comment by JoshVanL** [comment]
👋

**Comment by arfon** [comment]
Prize draw in 10 minutes folks!

**Comment by kewisch** [comment]
Just in time 👋🏻

**Comment by faenil** [comment]
Woohoo :)

**Comment by shadeslayer** [comment]
@shadeslayer

**Comment by rowlando** [comment]
Hello!

**Comment by arfon** [comment]
No.more.entries!

**Comment by arfon** [comment]
@Revana-Siddesh-Bathi wins GitHub Pro!

**Comment by arfon** [comment]
@Kirol54 wins GitHub Pro!

**Comment by arfon** [comment]
@rowlando wins GitHub Pro!

**Comment by arfon** [comment]
@faenil wins GitHub Pro!

**Comment by arfon** [comment]
@lcrilly wins GitHub Pro!

**Comment by arfon** [comment]
@babolivier wins a cap!

**Comment by arfon** [comment]
@hrvdm wins a cap!

**Comment by arfon** [comment]
@kirederik wins a cap!

**Comment by arfon** [comment]
@t3chguy wins a badge!

**Comment by arfon** [comment]
@akrabat wins a badge!

**Comment by arfon** [comment]
@shadeslayer wins a badge!

**Comment by arfon** [comment]
@danuw wins a badge!

**Comment by arfon** [comment]
@igmitchell wins a GitHub neon sign!

**Comment by arfon** [comment]
@JDuchniewicz wins a GitHub neon sign!

**Comment by dcharbon** [comment]
Thank you, GitHub!

**Comment by martinwoodward** [comment]
Thanks for coming to the show folks. And thanks for all the work you do in the open source community
